//! Proc macros for higgs.
//!
//! ## `#[derive(TsConstEnum)]`
//!
//! Emit a TypeScript **const-object** + derived type file for a Rust unit-variant
//! enum — instead of the plain `type X = "a" | "b"` union ts-rs produces. The
//! const-object form lets the frontend use the enum as a VALUE (`Foo.Bar`), not
//! just a type. This is ported from jigglebot's `macros` crate so higgs's enum
//! bindings are CONSISTENT with jigglebot's (higgs is a standalone crate and
//! cannot depend on jigglebot's `macros`, so the derive lives here).
//!
//! Pairs with `ts_rs::TS`: the enum keeps `#[derive(ts_rs::TS)]` +
//! `#[ts(export_to = "…")]` (so ts-rs knows the type + import path for dependent
//! structs) but MUST NOT carry `#[ts(export)]` — that would make ts-rs write a
//! competing union file that races this macro's writer. higgs's `higgs_ts!` enum
//! arm wires exactly this combination.
//!
//! ## Generated TS
//!
//! ```text
//! // AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
//! export const FlashAttn = {
//!     Auto : "auto",
//!     Off  : "off",
//!     On   : "on",
//! } as const;
//!
//! export const { Auto, Off, On } = FlashAttn;
//!
//! export type FlashAttn = (typeof FlashAttn)[keyof typeof FlashAttn];
//! ```
//!
//! ## `macro_run_*` test convention
//!
//! The derive emits a hidden `#[cfg(test)] #[ignore]` test named
//! `macro_run_ts_const_enum_<snake>` that writes the .ts file. It is run in a
//! SEPARATE pass (`cargo test macro_run -- --ignored`) so no ts-rs auto-export
//! writer is active and the single `fs::write` wins deterministically.
//!
//! ## Path anchoring
//!
//! ts-rs anchors `export_to` at `<crate>/bindings/`; this macro anchors at
//! `CARGO_MANIFEST_DIR` (`<crate>/`). higgs's `export_to` is `bindings/`-relative
//! (e.g. `"higgs/"` → `<crate>/bindings/higgs/`), so we PREPEND `bindings/` to
//! resolve to the same final directory.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::{parse_macro_input, spanned::Spanned, Data, DeriveInput, Fields, LitStr, Meta};

/// Derive a TypeScript const-object file emitter for a Rust unit-variant enum.
#[proc_macro_derive(TsConstEnum)]
pub fn derive_ts_const_enum(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand(&input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// Expand the body of `#[derive(TsConstEnum)]`.
fn expand(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let enum_name = &input.ident;
    let enum_name_str = enum_name.to_string();

    // 1. Validate: enum + unit-variants only.
    let Data::Enum(data) = &input.data else {
        return Err(syn::Error::new(
            input.span(),
            "#[derive(TsConstEnum)] only supports enums",
        ));
    };
    for v in &data.variants {
        if !matches!(v.fields, Fields::Unit) {
            return Err(syn::Error::new(
                v.span(),
                "#[derive(TsConstEnum)] only supports unit-variant enums — \
                 variants with fields produce discriminated unions which the \
                 const-object pattern cannot represent",
            ));
        }
    }

    // 2. Read ts-rs's #[ts(export_to = "…")] attribute so this macro + ts-rs
    //    agree on where the file lives (the enum only declares the path once).
    let ts_export_to = find_ts_export_to(&input.attrs).ok_or_else(|| {
        syn::Error::new(
            input.span(),
            "missing #[ts(export_to = \"<path>\")] attribute — needed so ts-rs \
             and TsConstEnum agree on where the file lives",
        )
    })?;
    let export_to = reanchor_ts_path(&ts_export_to);

    // 3. Read #[serde(rename_all = "…")] on the enum.
    let rename_all = find_serde_rename_all(&input.attrs);

    // 4. For each variant, compute key (Rust name) + wire value (serde rename).
    let mut pairs: Vec<(String, String)> = Vec::new();
    for v in &data.variants {
        let key = v.ident.to_string();
        let wire = find_serde_rename(&v.attrs)
            .unwrap_or_else(|| apply_rename_all(&key, rename_all.as_deref()));
        pairs.push((key, wire));
    }

    // 5. Build the .ts file contents.
    let mut ts_body = String::new();
    ts_body.push_str("// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.\n");
    ts_body.push_str("// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.\n\n");
    ts_body.push_str(&format!("export const {enum_name_str} = {{\n"));
    let key_pad = pairs.iter().map(|(k, _)| k.len()).max().unwrap_or(0);
    for (key, wire) in &pairs {
        ts_body.push_str(&format!("    {key:<pad$} : \"{wire}\",\n", pad = key_pad));
    }
    ts_body.push_str("} as const;\n\n");
    ts_body.push_str(&format!(
        "export const {{ {} }} = {enum_name_str};\n\n",
        pairs
            .iter()
            .map(|(k, _)| k.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    ts_body.push_str(&format!(
        "export type {enum_name_str} = (typeof {enum_name_str})[keyof typeof {enum_name_str}];\n"
    ));

    // 6. Emit the hidden #[ignore] writer test (run via `cargo test macro_run -- --ignored`).
    let test_fn_name = format_ident!("macro_run_ts_const_enum_{}", to_snake_case(&enum_name_str));
    let filename = format!("{enum_name_str}.ts");
    let ts_body_lit = LitStr::new(&ts_body, enum_name.span());
    let export_to_lit = LitStr::new(&export_to, enum_name.span());
    let filename_lit = LitStr::new(&filename, enum_name.span());

    Ok(quote! {
        #[cfg(test)]
        #[allow(non_snake_case)]
        #[test]
        #[ignore = "macro_run: invoke via `cargo test macro_run -- --ignored`"]
        fn #test_fn_name() {
            let manifest_dir = ::std::env!("CARGO_MANIFEST_DIR");
            let dir = ::std::path::Path::new(manifest_dir).join(#export_to_lit);
            ::std::fs::create_dir_all(&dir)
                .expect("TsConstEnum: failed to create output directory");
            let path = dir.join(#filename_lit);
            ::std::fs::write(&path, #ts_body_lit)
                .expect("TsConstEnum: failed to write generated .ts file");
        }
    })
}

/// Derive a per-field help-text emitter for a named-field struct, or a
/// per-variant one for a unit-variant enum (e.g. `FitVerdict` — the frontend
/// tooltips a verdict chip with the variant's explanation).
///
/// Reads `#[help = "…"]` on each field/variant and emits:
///   * a Rust `impl <Struct> { pub const PARAM_HELP: &[(&str,&str)] = …; }`
///     (unit-testable in the consuming crate), and
///   * a `#[ignore]` `macro_run_ts_param_help_<snake>` test that writes
///     `<export_to>/<Struct>Help.ts` — a const-object map the frontend reads at
///     runtime (ts-rs JSDoc is compile-time-only and unusable for a tooltip).
///
/// `#[help]` is registered as an inert helper attribute, so it never reaches
/// ts-rs/serde and needs no other handling. The wire format is untouched.
#[proc_macro_derive(TsParamHelp, attributes(help))]
pub fn derive_ts_param_help(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match expand_param_help(&input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

fn expand_param_help(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let struct_name = &input.ident;
    let struct_name_str = struct_name.to_string();

    // Reuse ts-rs's export_to so the .ts lands beside the type's own binding.
    let ts_export_to = find_ts_export_to(&input.attrs).ok_or_else(|| {
        syn::Error::new(
            input.span(),
            "missing #[ts(export_to = \"<path>\")] attribute — needed so the help \
             map lands in the same dir as the type binding",
        )
    })?;
    let export_to = reanchor_ts_path(&ts_export_to);

    // Container-level #[serde(rename_all = "…")] applies to every field's wire
    // name (unless a field overrides it with its own #[serde(rename = "…")]).
    let rename_all = find_serde_rename_all(&input.attrs);

    // Collect (wire_name, help) for every field/variant carrying
    // `#[help = "..."]`. The wire name mirrors what serde/ts-rs serialize: an
    // explicit rename wins, else the container rename_all rule applied to the
    // ident, else the ident verbatim.
    let mut pairs: Vec<(String, String)> = Vec::new();
    match &input.data {
        Data::Struct(data) => {
            let Fields::Named(named) = &data.fields else {
                return Err(syn::Error::new(
                    input.span(),
                    "#[derive(TsParamHelp)] only supports named-field structs",
                ));
            };
            for f in &named.named {
                let Some(help) = find_field_help(&f.attrs) else {
                    continue;
                };
                let ident = f
                    .ident
                    .as_ref()
                    .expect("named field has an ident")
                    .to_string();
                let wire = find_serde_rename(&f.attrs)
                    .unwrap_or_else(|| apply_rename_all_field(&ident, rename_all.as_deref()));
                pairs.push((wire, help));
            }
        }
        Data::Enum(data) => {
            for v in &data.variants {
                let Fields::Unit = &v.fields else {
                    return Err(syn::Error::new(
                        v.ident.span(),
                        "#[derive(TsParamHelp)] on an enum supports unit variants only",
                    ));
                };
                let Some(help) = find_field_help(&v.attrs) else {
                    continue;
                };
                let wire = find_serde_rename(&v.attrs).unwrap_or_else(|| {
                    apply_rename_all_variant(&v.ident.to_string(), rename_all.as_deref())
                });
                pairs.push((wire, help));
            }
        }
        Data::Union(_) => {
            return Err(syn::Error::new(
                input.span(),
                "#[derive(TsParamHelp)] supports structs and enums, not unions",
            ));
        }
    }

    // Rust const (unit-testable in the consuming crate).
    let keys: Vec<&str> = pairs.iter().map(|(k, _)| k.as_str()).collect();
    let vals: Vec<&str> = pairs.iter().map(|(_, v)| v.as_str()).collect();

    // .ts const-object body (pure string render — see render_help_ts).
    let ts_body = render_help_ts(&struct_name_str, &pairs);

    let test_fn_name = format_ident!(
        "macro_run_ts_param_help_{}",
        to_snake_case(&struct_name_str)
    );
    let filename = format!("{struct_name_str}Help.ts");
    let ts_body_lit = LitStr::new(&ts_body, struct_name.span());
    let export_to_lit = LitStr::new(&export_to, struct_name.span());
    let filename_lit = LitStr::new(&filename, struct_name.span());

    Ok(quote! {
        impl #struct_name {
            /// Per-field one-line help, surfaced to the frontend via the generated
            /// `<Struct>Help.ts`. Generated by `#[derive(TsParamHelp)]`. The const's
            /// reference lifetimes elide to `'static` — left implicit so clippy's
            /// `redundant_static_lifetimes` stays quiet under the `-D warnings` gate.
            pub const PARAM_HELP: &[(&str, &str)] = &[ #((#keys, #vals)),* ];
        }

        #[cfg(test)]
        #[allow(non_snake_case)]
        #[test]
        #[ignore = "macro_run: invoke via `cargo test macro_run -- --ignored`"]
        fn #test_fn_name() {
            let manifest_dir = ::std::env!("CARGO_MANIFEST_DIR");
            let dir = ::std::path::Path::new(manifest_dir).join(#export_to_lit);
            ::std::fs::create_dir_all(&dir)
                .expect("TsParamHelp: failed to create output directory");
            let path = dir.join(#filename_lit);
            ::std::fs::write(&path, #ts_body_lit)
                .expect("TsParamHelp: failed to write generated .ts file");
        }
    })
}

/// Read `#[help = "..."]` off a field's attributes.
fn find_field_help(attrs: &[syn::Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("help") {
            continue;
        }
        if let Meta::NameValue(nv) = &attr.meta {
            if let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(s),
                ..
            }) = &nv.value
            {
                return Some(s.value());
            }
        }
    }
    None
}

/// Render the const-object `<Struct>Help.ts` body from `(wire_key, help)` pairs.
///
/// BOTH the property key and the value are emitted as escaped double-quoted
/// string literals. Quoting the key is required for correctness: unlike
/// `TsConstEnum` (whose keys are always-valid Rust variant idents), these keys
/// are serde WIRE names, which the macro is designed to honor (`find_serde_rename`).
/// A wire name that is not a valid TS identifier — e.g. `#[serde(rename = "max-tokens")]`
/// — emitted bare (`max-tokens: "…"`) would parse as a subtraction expression and
/// make the file invalid; `"max-tokens": "…"` is always valid. Dot access
/// (`Help.ctx_len`) still works for identifier keys when they are quoted in the
/// object literal, so no consumer changes.
fn render_help_ts(struct_name_str: &str, pairs: &[(String, String)]) -> String {
    let mut ts_body = String::new();
    ts_body.push_str("// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.\n");
    ts_body.push_str("// Per-field help via `#[derive(TsParamHelp)]` in `higgs-macros`.\n\n");
    ts_body.push_str(&format!("export const {struct_name_str}Help = {{\n"));
    for (k, v) in pairs {
        let key = escape_ts_string(k);
        let val = escape_ts_string(v);
        ts_body.push_str(&format!("    \"{key}\": \"{val}\",\n"));
    }
    ts_body.push_str("} as const;\n\n");
    ts_body.push_str(&format!(
        "export type {struct_name_str}HelpKey = keyof typeof {struct_name_str}Help;\n"
    ));
    ts_body
}

/// Escape a string for embedding inside a double-quoted TypeScript string literal.
///
/// Handles every character that a single-line `"…"` literal cannot carry raw:
/// backslash, double-quote, the C0 control range (incl. `\n`/`\r`/`\t`), and the
/// JS line separators U+2028/U+2029 (illegal unescaped in TS string literals).
/// Common control chars get their short escape; the rest get `\uXXXX`. This keeps
/// the generated `*Help.ts` valid for ANY help text, not just today's prose.
fn escape_ts_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{0000}'..='\u{001F}' | '\u{2028}' | '\u{2029}' => {
                out.push_str(&format!("\\u{:04x}", ch as u32));
            }
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
#[path = "lib_tests.rs"]
mod tests;

// ── Attribute parsers ────────────────────────────────────────────────────────

/// Read `export_to = "..."` out of ts-rs's `#[ts(...)]` attribute. Other `#[ts]`
/// keys (`export`, `rename`, `optional`, `type`, …) are skipped without error.
fn find_ts_export_to(attrs: &[syn::Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("ts") {
            continue;
        }
        let mut found: Option<String> = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("export_to") {
                let value = meta.value()?;
                let s: LitStr = value.parse()?;
                found = Some(s.value());
            } else if meta.input.peek(syn::Token![=]) {
                let _ = meta
                    .value()
                    .and_then(syn::parse::ParseBuffer::parse::<Meta>);
            }
            Ok(())
        });
        if found.is_some() {
            return found;
        }
    }
    None
}

/// Re-anchor ts-rs's `export_to` so it resolves to the same final directory but
/// relative to `CARGO_MANIFEST_DIR` instead of ts-rs's `<crate>/bindings/` anchor.
/// higgs's paths are `bindings/`-relative (e.g. `"higgs/"`), so prepend `bindings/`.
fn reanchor_ts_path(ts_path: &str) -> String {
    format!("bindings/{ts_path}")
}

fn find_serde_rename_all(attrs: &[syn::Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let mut rename_all: Option<String> = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename_all") {
                let value = meta.value()?;
                let s: LitStr = value.parse()?;
                rename_all = Some(s.value());
            } else {
                let _ = meta
                    .value()
                    .and_then(syn::parse::ParseBuffer::parse::<Meta>);
            }
            Ok(())
        });
        if rename_all.is_some() {
            return rename_all;
        }
    }
    None
}

fn find_serde_rename(attrs: &[syn::Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let mut rename: Option<String> = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                let value = meta.value()?;
                let s: LitStr = value.parse()?;
                rename = Some(s.value());
            } else {
                let _ = meta
                    .value()
                    .and_then(syn::parse::ParseBuffer::parse::<Meta>);
            }
            Ok(())
        });
        if rename.is_some() {
            return rename;
        }
    }
    None
}

// ── Case conversion (matches serde's rename_all rules) ────────────────────────

fn apply_rename_all(name: &str, rule: Option<&str>) -> String {
    match rule {
        None | Some("PascalCase") => name.to_string(),
        Some("lowercase") => name.to_lowercase(),
        Some("UPPERCASE") => name.to_uppercase(),
        Some("camelCase") => to_camel_case(name),
        Some("snake_case") => to_snake_case(name),
        Some("SCREAMING_SNAKE_CASE") => to_snake_case(name).to_uppercase(),
        Some("kebab-case") => to_snake_case(name).replace('_', "-"),
        Some("SCREAMING-KEBAB-CASE") => to_snake_case(name).replace('_', "-").to_uppercase(),
        Some(_) => name.to_string(),
    }
}

/// Apply a serde container `rename_all` rule to a STRUCT FIELD identifier,
/// mirroring serde's `RenameRule::apply_to_field`. Distinct from
/// [`apply_rename_all`], which targets PascalCase enum VARIANTS — struct fields
/// are snake_case at the source, so the word boundaries (and thus the camelCase/
/// PascalCase conversions) differ. Used so [`TsParamHelp`](derive_ts_param_help)
/// keys match the serialized/ts-rs wire names under a container rename.
/// Apply serde's container `rename_all` rule to a PascalCase VARIANT ident
/// (the variant analogue of [`apply_rename_all_field`]; serde leaves variants
/// untouched without a rule).
fn apply_rename_all_variant(variant: &str, rule: Option<&str>) -> String {
    match rule {
        None | Some("PascalCase") => variant.to_string(),
        Some("lowercase") => variant.to_lowercase(),
        Some("UPPERCASE") => variant.to_uppercase(),
        Some("snake_case") => pascal_to_snake(variant),
        Some("SCREAMING_SNAKE_CASE") => pascal_to_snake(variant).to_uppercase(),
        Some("camelCase") => {
            let mut c = variant.chars();
            match c.next() {
                Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        }
        Some(other) => panic!("TsParamHelp: unsupported rename_all rule {other:?}"),
    }
}

/// `PascalCase` → `snake_case` (serde's variant snake_case rule).
fn pascal_to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn apply_rename_all_field(field: &str, rule: Option<&str>) -> String {
    match rule {
        // serde leaves snake_case fields untouched for None/lowercase/snake_case.
        None | Some("lowercase") | Some("snake_case") => field.to_string(),
        Some("UPPERCASE") | Some("SCREAMING_SNAKE_CASE") => field.to_uppercase(),
        Some("PascalCase") => field_to_pascal(field),
        Some("camelCase") => {
            let pascal = field_to_pascal(field);
            let mut chars = pascal.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_lowercase().chain(chars).collect(),
            }
        }
        Some("kebab-case") => field.replace('_', "-"),
        Some("SCREAMING-KEBAB-CASE") => field.to_uppercase().replace('_', "-"),
        Some(_) => field.to_string(),
    }
}

/// Convert a snake_case field identifier to PascalCase (`ctx_len` → `CtxLen`),
/// matching serde's field PascalCase rule (capitalize each `_`-separated word).
fn field_to_pascal(field: &str) -> String {
    let mut out = String::with_capacity(field.len());
    let mut capitalize = true;
    for ch in field.chars() {
        if ch == '_' {
            capitalize = true;
        } else if capitalize {
            out.extend(ch.to_uppercase());
            capitalize = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_snake_case(pascal: &str) -> String {
    let mut out = String::with_capacity(pascal.len() + 4);
    for (i, ch) in pascal.chars().enumerate() {
        if ch.is_uppercase() {
            if i != 0 {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_camel_case(pascal: &str) -> String {
    let mut chars = pascal.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().chain(chars).collect(),
    }
}
