// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogSort } from "./CatalogSort";

/**
 * One search against the Hub model catalog. Sent by jigglebot's Model
 * Search tab (and built by the CLI). Every field except `search` has a
 * serde default so a caller can send just the query text.
 */
export type CatalogQuery = { 
/**
 * Free-text query (matches repo ids and descriptions on the Hub).
 */
search: string, 
/**
 * Restrict to one author/organization (used for "more by publisher").
 */
author?: string, 
/**
 * Result ordering; absent = [`CatalogSort::Downloads`].
 */
sort?: CatalogSort, 
/**
 * Maximum rows to return, clamped to [`MAX_SEARCH_LIMIT`]; absent (or
 * `0`) = the default page size.
 */
limit?: number, 
/**
 * `true` = drop rows whose smallest shipped quant is ESTIMATED not to
 * fit this machine (rows without enough data for a verdict are kept —
 * unknown is never treated as incompatible). Absent/`false` = all rows.
 * NB the filtered set is best-effort, not deterministic click-to-click:
 * a row whose enrichment times out on one search is kept as unknown,
 * and may enrich (and drop) on the next.
 */
compatible_only?: boolean, };
