// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Hub's GGUF metadata block for a repo (`gguf` on the model-info
 * response) reduced to the fields the UI badges: architecture, total
 * parameter count, and training context length. Present only on repos
 * where the Hub reports it (detail responses; search rows omit it).
 */
export type CatalogGgufMeta = { 
/**
 * Model architecture (e.g. `"llama"`, `"qwen3"`).
 */
arch?: string, 
/**
 * Total parameter count (e.g. `8030261248` for an 8B model).
 */
params_total?: number, 
/**
 * Training context length in tokens.
 */
ctx_train?: number, };
