// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModelSummary } from "./CatalogModelSummary";
import type { CatalogQuant } from "./CatalogQuant";

/**
 * Full catalog detail for one repo — the right-hand detail pane.
 */
export type CatalogModelDetail = { 
/**
 * The repo's search-row fields (with `gguf` populated when reported).
 */
summary: CatalogModelSummary, 
/**
 * Hub tags (capability/library badges are derived from these).
 */
tags: Array<string>, 
/**
 * The repo README (markdown), truncated to a bounded size; `None`
 * when the repo has none or the fetch failed (best-effort).
 */
readme?: string, 
/**
 * Every `.gguf` file in the repo, one quant-picker row each.
 */
quants: Array<CatalogQuant>, 
/**
 * The file the download picker should preselect — higgs's
 * [`default_quant`](crate::catalog::service::default_quant) policy
 * (`Q4_K_M` → largest that fits → smallest). `None` when the repo
 * ships no downloadable quant.
 */
default_file?: string, 
/**
 * Other repos by the same author (self excluded) — "more by publisher".
 */
more_by_author: Array<CatalogModelSummary>, };
