// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitAssessment } from "./FitAssessment";

/**
 * One downloadable GGUF file of a repo — the quant-picker row.
 */
export type CatalogQuant = { 
/**
 * File name inside the repo (e.g. `"model-Q4_K_M.gguf"`).
 */
file: string, 
/**
 * Quantization label parsed from the file name (e.g. `"Q4_K_M"`),
 * when the name follows the common convention.
 */
quant?: string, 
/**
 * File size in bytes, when the Hub reported it.
 */
size_bytes?: number, 
/**
 * `true` when this exact file is already on this machine.
 */
downloaded: boolean, 
/**
 * Size-based fit verdict against this machine's VRAM headroom
 * (advisory, pre-download — the file size is a lower bound for the
 * resident footprint). `None` when the size or hardware is unknown.
 */
fit?: FitAssessment, };
