// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const CatalogSort = {
    Downloads : "downloads",
    Likes     : "likes",
    Updated   : "updated",
    Trending  : "trending",
} as const;

export const { Downloads, Likes, Updated, Trending } = CatalogSort;

export type CatalogSort = (typeof CatalogSort)[keyof typeof CatalogSort];
