// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModelSummary } from "./CatalogModelSummary";

/**
 * Catalog search response: the mapped rows, newest query wins in the UI.
 */
export type CatalogSearchResponse = { 
/**
 * Search rows in the requested sort order.
 */
models: Array<CatalogModelSummary>, };
