// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogGgufMeta } from "./CatalogGgufMeta";
import type { FitAssessment } from "./FitAssessment";

/**
 * One catalog search row: a Hub GGUF model repo plus whether any quant of
 * it is already on this machine.
 */
export type CatalogModelSummary = { 
/**
 * Hub repo id (`org/model`) — also the higgs model id after download.
 */
id: string, 
/**
 * Repo author/organization.
 */
author?: string, 
/**
 * All-time download count on the Hub.
 */
downloads?: number, 
/**
 * Like count on the Hub.
 */
likes?: number, 
/**
 * Last-modified timestamp (ISO-8601, verbatim from the Hub).
 */
updated?: string, 
/**
 * The Hub pipeline tag (e.g. `"text-generation"`).
 */
pipeline?: string, 
/**
 * GGUF metadata badge fields, when the Hub response carried them.
 */
gguf?: CatalogGgufMeta, 
/**
 * Advisory repo-level fit verdict: the ESTIMATED footprint of the
 * smallest quant the repo ships (parameter count × the quant family's
 * effective bytes-per-weight) against this machine's VRAM headroom.
 * `None` when the estimate has no inputs (no parameter count, no
 * labeled quant, or no reported VRAM) — never a fake verdict. Detail
 * responses replace the estimate with the real smallest-file size.
 */
fit?: FitAssessment, 
/**
 * `true` when the local scan already has a model under this repo id.
 */
downloaded: boolean, };
