// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The context window to load with. Replaces the old `ctx_len: u32` where `0` was a
 * sentinel for "AUTO" (let the engine pick the model's trained context, capped) — the
 * intent now lives in the type. A data enum, so a ts-rs tagged union (the const-enum
 * exception), internally tagged on `kind`: `{"kind":"auto"}` / `{"kind":"fixed","n":4096}`.
 * Mapped to the raw `with_n_ctx` int ONLY inside `llamacpp/mod.rs`.
 */
export type CtxLen = { "kind": "auto" } | { "kind": "fixed", 
/**
 * Window size in tokens.
 */
n: number, };
