// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const DeviceKind = {
    Cpu   : "Cpu",
    Gpu   : "Gpu",
    Accel : "Accel",
} as const;

export const { Cpu, Gpu, Accel } = DeviceKind;

export type DeviceKind = (typeof DeviceKind)[keyof typeof DeviceKind];
