// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of compute device, mirroring ggml's `ggml_backend_dev_type`
 * (`GGML_BACKEND_DEVICE_TYPE_{CPU,GPU,ACCEL}`). The worker maps the raw
 * FFI enum to this engine-agnostic shape; the mapping lives only in
 * `llamacpp.rs` (the sole file allowed to name the FFI).
 */
export type DeviceKind = "Cpu" | "Gpu" | "Accel";
