// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadLedgerStatus } from "./DownloadLedgerStatus";

/**
 * One machine-local downloads-ledger entry ([`crate::catalog::ledger`]):
 * a live transfer (any process on this machine — node daemon, embedded
 * hub, `higgs download` CLI) or a terminal history record. `(repo, file)`
 * is the download identity (same `dest_path` rules as everywhere);
 * `pid` names the owning process while `status` is `downloading`.
 */
export type DownloadLedgerEntry = { repo: string, file: string, 
/**
 * Owning process while downloading (dead-pid entries are swept).
 */
pid: number, 
/**
 * That process's kernel start time (platform units) — the pid-reuse
 * disambiguator: liveness requires the pid AND its start time to
 * match, so a recycled pid never masquerades as a live transfer.
 * Absent on legacy entries / unqueryable platforms (pid-only then).
 */
pid_started_at?: number, started_at_ms: number, downloaded: number, 
/**
 * Absent when the server sent no content length.
 */
total?: number, status: DownloadLedgerStatus, 
/**
 * Set on every terminal status.
 */
ended_at_ms?: number, 
/**
 * Final on-disk path — [`DownloadLedgerStatus::Done`] only.
 */
path?: string, 
/**
 * Failure reason — [`DownloadLedgerStatus::Failed`] only.
 */
detail?: string, };
