// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const DownloadLedgerStatus = {
    Downloading : "downloading",
    Done        : "done",
    Failed      : "failed",
    Cancelled   : "cancelled",
} as const;

export const { Downloading, Done, Failed, Cancelled } = DownloadLedgerStatus;

export type DownloadLedgerStatus = (typeof DownloadLedgerStatus)[keyof typeof DownloadLedgerStatus];
