// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DRY (Don't Repeat Yourself) repetition-sampler parameters, mapped to
 * `LlamaSampler::dry(model, multiplier, base, allowed_length, last_n, breakers)`.
 */
export type DryParams = { 
/**
 * Penalty multiplier (0 disables).
 */
multiplier: number, 
/**
 * Exponential base for the penalty growth.
 */
base: number, 
/**
 * Minimum sequence length that triggers the penalty.
 */
allowed_length: number, 
/**
 * How many recent tokens DRY scans (`-1` = whole context).
 */
penalty_last_n: number, 
/**
 * Sequence-breaker strings that reset the DRY match window. Always
 * serialized (possibly `[]`) — honest required-array binding.
 */
sequence_breakers: Array<string>, };
