// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtxLen } from "./CtxLen";
import type { GpuLayers } from "./GpuLayers";
import type { KvCacheKind } from "./KvCacheKind";
import type { ResourceBudget } from "./ResourceBudget";

/**
 * Request for the `estimate` control-op (`Higgs::estimate`, formerly
 * `POST /api/higgs/models/estimate`): the memory footprint of a
 * CANDIDATE load (the user's current context window / KV types / GPU offload),
 * so the UI shows "≈ X GiB VRAM · Fits/Tight/Overflow" live as they edit. Pure +
 * cheap (no model load) — higgs OWNS the formula (reuses the suggester's VRAM/RAM
 * estimators); the frontend never reimplements it. The verdict is measured against
 * the supplied `budget` (the app's % cap resolved to bytes — so the live verdict
 * matches the budget-aware tune), or the detected machine when no budget is sent.
 */
export type EstimateRequest = { 
/**
 * The model whose footprint to estimate (a scanned id).
 */
id: string, 
/**
 * Candidate context window.
 */
ctx_len: CtxLen, 
/**
 * Candidate GPU offload (`None` ⇒ all layers).
 */
gpu_layers?: GpuLayers, 
/**
 * Candidate KV key cache type (`None` ⇒ F16).
 */
type_k?: KvCacheKind, 
/**
 * Candidate KV value cache type (`None` ⇒ F16).
 */
type_v?: KvCacheKind, 
/**
 * Candidate KV-cache offload (`Some(false)` keeps KV in host RAM, not VRAM;
 * `None` ⇒ on GPU, the default). Memory-affecting, so the estimate honors it.
 */
offload_kqv?: boolean, 
/**
 * Candidate MoE expert offload to CPU (a tuned, non-visible param that moves
 * expert weights off the GPU). `None` ⇒ off. Memory-affecting on MoE models.
 */
cpu_moe?: boolean, 
/**
 * Resource cap the verdict is measured against (the app's % budget resolved
 * to bytes). `None` ⇒ the detected machine — keeps the live estimate
 * consistent with the budget-aware tune when a budget is set.
 */
budget?: ResourceBudget, };
