// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitReport } from "./FitReport";

/**
 * Response for the `estimate` control-op (`Higgs::estimate`, formerly
 * `POST /api/higgs/models/estimate`): the VRAM + RAM footprint of the
 * candidate load against the detected machine (verdict + needed/basis bytes).
 */
export type EstimateReport = { 
/**
 * GPU-VRAM footprint + fit verdict.
 */
vram: FitReport, 
/**
 * Host-RAM footprint + fit verdict.
 */
ram: FitReport, };
