// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a VRAM fit decision: whether a model of a given size fits the
 * safe headroom over reported VRAM, plus the two byte figures the verdict
 * was computed from. Produced by [`fits_vram`].
 */
export type FitAssessment = { 
/**
 * `true` when `needed_bytes <= available_bytes`.
 */
fits: boolean, 
/**
 * The model's estimated memory need in bytes (the GGUF file size on
 * disk — a lower-bound proxy for resident weights).
 */
needed_bytes: number, 
/**
 * The safe VRAM budget: `vram_total_bytes` scaled by the headroom
 * fraction. `0` when no VRAM was reported (no GPU), so the verdict is
 * "does not fit" and the caller falls back to the RAM headroom guard.
 */
available_bytes: number, };
