// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitVerdict } from "./FitVerdict";

/**
 * A memory fit verdict plus the byte figures it was computed from.
 */
export type FitReport = { 
/**
 * Fits / Tight / Overflow.
 */
verdict: FitVerdict, 
/**
 * Estimated bytes the load needs against this budget.
 */
needed_bytes: number, 
/**
 * The budget basis in bytes (the VRAM/RAM cap or detected total).
 */
budget_bytes: number, };
