// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Per-field help via `#[derive(TsParamHelp)]` in `higgs-macros`.

export const FitVerdictHelp = {
    "Fits": "The estimated memory footprint uses at most 80% of your resource budget for this device. There is comfortable headroom for the OS, other apps, and cache growth during long chats — safe to load.",
    "Tight": "The estimated footprint lands between 80% and 95% of your resource budget. It should load and serve, but headroom is thin — memory pressure from other apps or very long prompts can tip it over; consider a smaller context length or a quantized KV cache.",
    "Overflow": "The estimated footprint exceeds 95% of your resource budget, so the load will most likely fail or force the system into swapping. Lower the context length, quantize the KV cache, offload fewer GPU layers, or raise the budget in Hardware settings.",
} as const;

export type FitVerdictHelpKey = keyof typeof FitVerdictHelp;
