// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tri-state memory fit verdict.
 */
export type FitVerdict = "Fits" | "Tight" | "Overflow";
