// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const FitVerdict = {
    Fits     : "Fits",
    Tight    : "Tight",
    Overflow : "Overflow",
} as const;

export const { Fits, Tight, Overflow } = FitVerdict;

export type FitVerdict = (typeof FitVerdict)[keyof typeof FitVerdict];
