// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const FlashAttn = {
    Auto : "auto",
    Off  : "off",
    On   : "on",
} as const;

export const { Auto, Off, On } = FlashAttn;

export type FlashAttn = (typeof FlashAttn)[keyof typeof FlashAttn];
