// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flash-attention policy, mirroring llama.cpp's `llama_flash_attn_type`
 * (AUTO = -1, DISABLED = 0, ENABLED = 1). Engine-agnostic at this layer;
 * mapped to the raw `llama_cpp_sys_2` value only inside `llamacpp.rs`.
 */
export type FlashAttn = "auto" | "off" | "on";
