// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetEventKind } from "./FleetEventKind";

/**
 * One live fleet event (T10), broadcast by the hub for real-time UIs: WHICH node
 * changed and WHAT kind of change. The event is a cache-invalidation signal, not a
 * data carrier — the hub has already folded the node's pushed snapshot into its
 * inventory cache when this fires, so a subscriber re-reads `nodes_view` (or its
 * serving layer's equivalent) for the actual state.
 */
export type FleetEvent = { 
/**
 * The node's canonical endpoint id (the [`NodeKey`], as `NodeView.endpoint_id`).
 */
endpoint_id: string, kind: FleetEventKind, };
