// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const FleetEventKind = {
    ChatStart       : "chat_start",
    ChatEnd         : "chat_end",
    WorkerLoaded    : "worker_loaded",
    WorkerUnloaded  : "worker_unloaded",
    HubStateChanged : "hub_state_changed",
    NodeConnected   : "node_connected",
    InventorySynced : "inventory_synced",
    NodeDropped     : "node_dropped",
} as const;

export const { ChatStart, ChatEnd, WorkerLoaded, WorkerUnloaded, HubStateChanged, NodeConnected, InventorySynced, NodeDropped } = FleetEventKind;

export type FleetEventKind = (typeof FleetEventKind)[keyof typeof FleetEventKind];
