// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One load-relevant GGUF header key/value, curated for the UI so a support
 * mismatch can be pinned to a specific field (e.g. `general.architecture =
 * gemma4`). Only keys that bear on loadability are surfaced — giant arrays
 * (token lists, merges) are deliberately skipped. `value` is the
 * human-readable rendering of the header value.
 */
export type GgufComponent = { 
/**
 * GGUF metadata key, e.g. `general.architecture` or `llama.block_count`.
 */
key: string, 
/**
 * The value as a display string.
 */
value: string, };
