// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKind } from "./DeviceKind";

/**
 * One compute device enumerated by the worker via ggml's backend-device FFI.
 *
 * Gathered by the WORKER process (the one linking llama.cpp/Metal) for the
 * host it runs on, so the values are engine-native and ready for future
 * remote workers. `vram_total_bytes`/`vram_free_bytes` are ggml's reported
 * device memory; for a unified-memory Apple GPU these track system RAM.
 */
export type GpuDevice = { 
/**
 * Backend device name (e.g. `"Metal"`, `"CUDA0"`).
 */
name: string, 
/**
 * Human-readable device description (e.g. `"Apple M3 Max"`).
 */
description: string, 
/**
 * Device kind (CPU / GPU / accelerator).
 */
kind: DeviceKind, 
/**
 * Total device memory in bytes, as ggml reports it.
 */
vram_total_bytes: number, 
/**
 * Free device memory in bytes at enumeration time.
 */
vram_free_bytes: number, };
