// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many model layers to offload to the GPU. Replaces the old `gpu_layers: u32`
 * where `u32::MAX` was a sentinel for "all" — the intent now lives in the type, not a
 * magic number. A data enum (carries `n`), so it is a ts-rs tagged union (the documented
 * exception to the const-enum rule), internally tagged on `kind`:
 * `{"kind":"all"}` / `{"kind":"count","n":32}`. Mapped to the raw `with_n_gpu_layers`
 * int ONLY inside `llamacpp/mod.rs`.
 */
export type GpuLayers = { "kind": "all" } | { "kind": "count", 
/**
 * Number of layers offloaded.
 */
n: number, };
