// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GBNF grammar constraint, mapped to `LlamaSampler::grammar(model, gbnf, root)`.
 * Lazy-trigger variants (words/tokens/patterns) are deferred (DESIGN §9).
 */
export type GrammarParams = { 
/**
 * The GBNF grammar source.
 */
gbnf: string, 
/**
 * The grammar root rule name (e.g. `"root"`).
 */
root: string, };
