// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuDevice } from "./GpuDevice";

/**
 * Host hardware snapshot.
 */
export type HardwareInfo = { 
/**
 * CPU brand string (e.g. `"Apple M3 Max"`).
 */
cpu_name: string, 
/**
 * Process architecture (e.g. `"aarch64"`).
 */
arch: string, 
/**
 * Logical CPU count.
 */
cpu_cores: number, 
/**
 * Total physical RAM in bytes.
 */
ram_total_bytes: number, 
/**
 * RAM currently in use, in bytes.
 */
ram_used_bytes: number, 
/**
 * Global CPU load at request time, 0–100.
 */
cpu_usage_percent: number, 
/**
 * Compute devices the worker enumerated via ggml's backend-device FFI.
 * Empty when no worker could be reached or no devices were reported.
 */
gpus: Array<GpuDevice>, 
/**
 * Sum of every enumerated GPU device's `vram_total_bytes`; `0` when no
 * GPU device is present. The headroom basis for [`fits_vram`].
 */
vram_total_bytes: number, };
