// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One in-flight download announced in [`HelloParams::downloads`] (and echoed
 * by `M_NODE_PULL_STATUS`): identity + live byte progress. Surfaced on
 * [`crate::node::fleet::NodeView::downloads`] so the Fleet UI shows a
 * transfer that survived a hub disconnect and the operator continues it.
 */
export type HelloDownload = { repo: string, file: string, downloaded: number, 
/**
 * Absent when the server sent no content length.
 */
total?: number, 
/**
 * `true` when the node's OWN process registry holds this transfer
 * (`node_registry().in_flight()`) and can cancel it via the future
 * M_NODE_PULL_CANCEL dispatch. `false` when the row is announced from
 * the machine LEDGER only — another process on the node box
 * (`higgs download` CLI, embedded hub) is doing the transfer and this
 * node has no cancel channel into it. The UI hides the cancel button
 * on non-cancellable rows; a future cancel dispatch refuses them with
 * a clear "not this process — cancel it where it was started"
 * message. Additive: default `false` so an older hub decoding a
 * newer node's payload treats every row as observe-only rather than
 * falsely offering a cancel that can't take.
 */
cancellable: boolean, };
