// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiggsKeyEntry } from "./HiggsKeyEntry";

/**
 * `GET /api/higgs/keys` — the configured keys plus whether auth is
 * currently gating the surface (false ⇔ zero keys ⇔ open).
 */
export type HiggsKeysList = { auth_enabled: boolean, keys: Array<HiggsKeyEntry>, };
