// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for the `settings` control-op (the runtime-settings read/write facade;
 * formerly `GET`/`PUT /api/higgs/settings`): the runtime server-behavior
 * flags higgs actually backs. The read returns the current state; the write
 * carries it and sets it. Distinct from [`LogSettings`] (Developer-Log toggles) —
 * this is the server-behavior namespace, designed to grow as more runtime
 * flags (e.g. a server on/off) are added.
 */
export type HiggsRuntimeSettings = { 
/**
 * Whether just-in-time model loading is enabled. When `true` (the
 * default), a chat request for a scanned-but-unloaded model loads it on
 * demand — swapping out any resident model (higgs serves one at a time) —
 * instead of returning a 404. When `false`, an unloaded model is a 404
 * (explicit-load only).
 */
jit_enabled: boolean, 
/**
 * Whether the idle reaper auto-unloads the loaded model after the idle
 * TTL (default `true`). When `false`, a loaded model stays resident
 * until an explicit unload regardless of idle time. Read by the reaper
 * each tick, so a change takes effect without a restart.
 */
auto_unload_idle: boolean, 
/**
 * Idle minutes after which the loaded model is auto-unloaded (default
 * 5, ollama `keep_alive`). Read by the reaper each tick. Only in effect
 * when [`auto_unload_idle`](Self::auto_unload_idle) is `true`.
 */
idle_ttl_minutes: number, 
/**
 * Whether the `/v1` inference surface is serving (default `true`). When
 * `false`, the `/v1` inference endpoints return `[HG019]` → 503 while the
 * in-process control surface stays reachable so the server can be
 * re-enabled. Read by the chat boundary on each request, so a change
 * takes effect without a restart.
 */
serving_enabled: boolean, };
