// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiggsModelEntry } from "./HiggsModelEntry";

/**
 * The `models` control-op response (`Higgs::model_entries`, formerly
 * `GET /api/higgs/models`): live scan results plus the loaded id.
 */
export type HiggsModelsResponse = { 
/**
 * Models discovered by a live scan of the configured directories.
 */
models: Array<HiggsModelEntry>, 
/**
 * Id of the currently loaded model, if any — matches `HiggsModel::id`.
 */
loaded_id?: string, 
/**
 * The ids chat can actually reach — `Higgs::chat_model_ids`, the SAME set
 * `/v1/models` advertises and the dispatch gates accept.
 *
 * A UI must gate its model picker on THIS list and never re-derive one
 * from `models[].readiness`: readiness is a per-scan-row verdict keyed by
 * id, while reachability is decided by the LOADED worker's facts and the
 * fleet's routes. The two legitimately disagree — a resident embedding
 * worker under an id whose first scan variant is a generative file reads
 * `Loaded` on that row, yet every chat to it is refused ([HG079]). Only
 * the crate can join those sources, so it ships the answer.
 */
chat_model_ids: Array<string>, };
