// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `DELETE /api/higgs/keys/{label}` response: how many keys the label matched.
 * Revoking the last key turns auth OFF on a LOOPBACK bind only; a
 * LAN-exposed server REFUSES last-key revocation outright ([HG059], 409) —
 * the runtime counterpart of the [HG058] startup guarantee.
 */
export type HiggsKeyRemoved = { removed: number, auth_enabled: boolean, };
