// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error body for control routes: the rendered `HiggsError` display
 * (diagnostic code included), as `{"error":"<display>"}`.
 */
export type HiggsErrorResponse = { 
/**
 * Human-readable failure, e.g. `[HG003] model not loaded: …`.
 */
error: string, };
