// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * One configured API key as the management surface lists it: label,
 * scopes, and a short digest prefix as its display identifier. NEVER the
 * plaintext token (shown once at mint) and never the full digest.
 */
export type HiggsKeyEntry = { label: string, scopes: Array<Scope>, 
/**
 * First 12 hex chars of the stored SHA-256 digest.
 */
sha256_prefix: string, };
