// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for the `load` control-op (formerly `POST /api/higgs/models/load`):
 * `{"status":"ok","id":…}`.
 */
export type HiggsLoadResponse = { 
/**
 * Id of the model that was loaded.
 */
id: string, 
/**
 * Literal `"ok"`.
 */
status: string, };
