// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events the host application subscribes to.
 */
export type HiggsEvent = { "ModelLoaded": { id: string, } } | { "ModelUnloaded": { id: string, } } | "WorkerDied" | "WorkerRestarted";
