// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiggsModelEntry } from "./HiggsModelEntry";

/**
 * The `models` control-op response (`Higgs::model_entries`, formerly
 * `GET /api/higgs/models`): live scan results plus the loaded id.
 */
export type HiggsModelsResponse = { 
/**
 * Models discovered by a live scan of the configured directories.
 */
models: Array<HiggsModelEntry>, 
/**
 * Id of the currently loaded model, if any — matches `HiggsModel::id`.
 */
loaded_id?: string, };
