// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadedInfo } from "./LoadedInfo";

/**
 * Live status snapshot returned by [`Higgs::status`].
 */
export type HiggsStatus = { 
/**
 * Whether the worker process is currently alive.
 */
worker_alive: boolean, 
/**
 * Info about the loaded model, if any.
 */
loaded?: LoadedInfo, 
/**
 * Number of models discovered in the last scan.
 */
models_on_disk: number, };
