// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GgufComponent } from "./GgufComponent";
import type { HiggsModelSource } from "./HiggsModelSource";

/**
 * Per-model entry in `GET /api/higgs/models`: enriches [`HiggsModel`] with
 * request-derived fields computed by the control handler.
 */
export type HiggsModelEntry = { 
/**
 * Load state: `"loaded"` if this model is currently resident, `"not-loaded"` otherwise.
 */
state: string, 
/**
 * File format — always `"gguf"` for higgs-discovered models.
 */
format: string, 
/**
 * Gate 1: whether our llama.cpp engine can LOAD this model, as proved by
 * a real probe of a representative GGUF for this `(arch, quant)`. `false`
 * means a load attempt failed; `support_reason` carries the verbatim
 * engine reason.
 */
loadable: boolean, 
/**
 * Gate 2: whether higgs has a tool-call parser that matches this model's
 * chat template. `false` means the model loads but tool calls can't be
 * parsed; `support_reason` explains.
 */
tool_calls: boolean, 
/**
 * The exact reason this model isn't fully supported, or `None` when it is.
 * When `!loadable`, this is the engine's VERBATIM load error (e.g.
 * `"unknown model architecture: 'gemma4'"`). When `loadable && !tool_calls`,
 * it is `"no tool-call parser matches this model's template"`.
 *
 * The curated `gguf_components` list — used by the UI to pin a support
 * mismatch to a specific header field — rides the flattened
 * [`HiggsModel`] (its single home); it is not re-declared here.
 */
support_reason?: string, 
/**
 * HuggingFace repo id, `org/model` — the identity used everywhere.
 * Ollama-sourced models keep their established Ollama name (`ollama/{name}:{tag}`);
 * no HuggingFace id is fabricated.
 */
id: string, 
/**
 * Absolute path to the GGUF file.
 */
path: string, 
/**
 * File size in bytes.
 */
size_bytes: number, 
/**
 * Quantization tag parsed from the filename (e.g. `Q4_K_M`), if present.
 */
quant?: string, 
/**
 * Which store the file was found in.
 */
source: HiggsModelSource, 
/**
 * Model architecture read from GGUF header (e.g. `"llama"`, `"gemma3"`).
 * `None` when the header could not be read or the field is absent.
 */
arch?: string, 
/**
 * Training context length (`{arch}.context_length`) from the GGUF header.
 * `None` when the header could not be read or the field is absent.
 */
ctx_train?: number, 
/**
 * Whether `tokenizer.chat_template` is present in the GGUF header.
 * `false` when the header could not be read.
 */
has_chat_template: boolean, 
/**
 * Whether the chat template declares tool/function calling. Heuristic: the
 * embedded template references tool calls (`tool_call`/`tools`). `false`
 * when there is no template or it carries no tool markup. `serde(default)`
 * so older scan payloads without the field deserialize as `false`.
 */
supports_tools: boolean, 
/**
 * Whether the model emits a reasoning/thinking block. Heuristic: the
 * template references `<think>`/thinking. `false` when unknown.
 */
supports_reasoning: boolean, 
/**
 * Curated load-relevant GGUF header fields (architecture, quant, tokenizer,
 * block/head counts, gguf version) for the UI to pin a support mismatch to a
 * specific component. Empty when the header could not be read. `serde(default)`
 * so older scan payloads without the field deserialize as empty.
 */
gguf_components: Array<GgufComponent>, };
