// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * The key-mint control-op response (`Higgs::mint_key`, formerly
 * `POST /api/higgs/keys`). `token` is the plaintext — shown THIS
 * ONCE, never persisted, never logged; the caller must store it now.
 */
export type HiggsMintKeyResponse = { label: string, scopes: Array<Scope>, token: string, };
