// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confirmation body for mutating control routes; serializes as
 * `{"status":"ok"}`. Standalone equivalent of the gateway's `StatusOk`
 * (higgs imports nothing from jigglebot); responses with extra fields
 * compose it via `#[serde(flatten)]`.
 */
export type HiggsOk = { 
/**
 * Literal `"ok"`.
 */
status: string, };
