// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HiggsLimits } from "./HiggsLimits";
import type { LoadParams } from "./LoadParams";

/**
 * Read-only snapshot of the server's effective configuration, surfaced by the
 * `system` control-op so the UI can show the real scan dirs, load
 * defaults, bind host, and safety limits without inventing anything. Derived
 * entirely from [`HiggsConfig`] plus the fixed invariants ([`BIND_HOST`],
 * [`DEFAULT_CTX_CAP`]) and the documented serve-layer limit consts; carries
 * no mutable state and no mutating endpoint.
 */
export type HiggsServerConfig = { 
/**
 * Loopback host the listener binds to — always [`BIND_HOST`] (localhost).
 */
bind_host: string, 
/**
 * Configured LM Studio scan directories, as absolute path strings.
 */
lmstudio_dirs: Array<string>, 
/**
 * Configured HuggingFace Hub cache scan directories, as path strings.
 */
hf_dirs: Array<string>, 
/**
 * Configured Ollama store scan directories, as path strings.
 */
ollama_dirs: Array<string>, 
/**
 * Load parameters applied when a load request omits them.
 */
default_load: LoadParams, 
/**
 * Context-window cap applied to an auto (unpinned) load — a huge-context
 * model's window is the trained length but never exceeds this.
 */
default_ctx_cap: number, 
/**
 * Serve-layer safety limits (read-only disclosure of the hardening).
 */
limits: HiggsLimits, };
