// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only snapshot of the serve-layer safety limits, surfaced inside
 * [`HiggsServerConfig`] so the Server Settings UI can show the actual
 * hardening posture of the no-auth loopback server. Every field mirrors a
 * documented `const` in this module (or `serve::mod`); none is yet mutable
 * at runtime — this is honest disclosure, not a control surface.
 */
export type HiggsLimits = { 
/**
 * Max request-body bytes before a `413` (`serve::MAX_BODY_BYTES`).
 */
max_body_bytes: number, 
/**
 * Whole-request timeout for the `/api/higgs/*` control surface, in
 * seconds (`serve::CONTROL_TIMEOUT`). The streaming `/v1` chat path is
 * deliberately un-timed at the HTTP layer.
 */
control_timeout_secs: number, 
/**
 * Worker chat-RPC timeout in seconds — the bound on a single generation
 * (`supervisor::CHAT_RPC_TIMEOUT`); a timeout is `[HG016]` → 504.
 */
chat_timeout_secs: number, 
/**
 * Absolute upper cap on a request's `max_tokens` ([`MAX_OUTPUT_TOKENS`]).
 */
max_output_tokens: number, 
/**
 * Max concurrent in-flight chat requests before a `503` busy
 * ([`MAX_CONCURRENT_INFERENCE`]).
 */
max_concurrent_inference: number, 
/**
 * Fraction of available RAM a load may claim before `[HG017]` → 503
 * ([`MEMORY_HEADROOM_FRACTION`]).
 */
memory_headroom_fraction: number, 
/**
 * Idle minutes after which the loaded model is auto-unloaded
 * ([`IDLE_UNLOAD_TTL`]).
 */
idle_unload_ttl_secs: number, };
