// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GgufComponent } from "./GgufComponent";
import type { HiggsModelSource } from "./HiggsModelSource";
import type { LoadParams } from "./LoadParams";
import type { ModelFit } from "./ModelFit";
import type { ModelReadiness } from "./ModelReadiness";
import type { TuneProvenance } from "./TuneProvenance";

/**
 * Per-model entry in `GET /api/higgs/models`: enriches [`HiggsModel`] with
 * request-derived fields computed by the control handler.
 */
export type HiggsModelEntry = { 
/**
 * Load state: `"loaded"` if this model is currently resident, `"not-loaded"` otherwise.
 */
state: string, 
/**
 * File format — always `"gguf"` for higgs-discovered models.
 */
format: string, 
/**
 * Gate 2: whether higgs has a tool-call parser that matches this model's
 * chat template. `false` means the model can be served but tool calls
 * can't be parsed; `support_reason` explains. (There is no scan-time
 * load probe — engine loadability is learned only at actual load.)
 */
tool_calls: boolean, 
/**
 * The fixed Gate-2 message when `!tool_calls`
 * (`"no tool-call parser matches this model's template"`), else `None`.
 * There is no scan-time load probe, so this never carries an engine load
 * error — a failed load is reported by the load endpoint itself.
 *
 * The curated `gguf_components` list — used by the UI to pin a support
 * mismatch to a specific header field — rides the flattened
 * [`HiggsModel`] (its single home); it is not re-declared here.
 */
support_reason?: string, 
/**
 * The params this model was last successfully loaded with on THIS instance,
 * persisted in `config.json` (`None` if it has never been loaded here).
 * Lets the UI show "last loaded with ctx=…, gpu_layers=…" for any scanned
 * model — replacing the removed scan-time load probe with real load history.
 * A `ctx_len` of `0` means AUTO (the engine picks the model's trained
 * context, capped) — the UI should render that as "auto", not "0".
 */
last_load?: LoadParams, 
/**
 * Readiness state for this model on THIS node — the contract the UI badges
 * and (future) autonomous agents read. Derived from profile presence,
 * staleness, residency, live resource fit, and the serving toggle.
 */
readiness: ModelReadiness, 
/**
 * The resource fit numbers behind a `servable`/`unservable` readiness —
 * `Some` only when a profile was evaluated for fit, so the UI can show
 * the needed-vs-free gap. `None` for the other states.
 */
fit?: ModelFit, 
/**
 * The last ANALYTICAL tune's load params (the engine-tagged umbrella).
 * Together with `benched_load` these are the two selectable saved
 * param sets both load surfaces offer; `tune_provenance` says which
 * one is the ACTIVE profile (the JIT/readiness default). `None` when
 * no analytical tune has run.
 */
tuned_load?: LoadParams, 
/**
 * The last TURBOTUNE (measured benchmark) config's load params — the
 * "Benchmarked" selectable set; `bench_tps` is its measured decode
 * throughput. `None` when the model was never benchmarked.
 */
benched_load?: LoadParams, 
/**
 * How the ACTIVE ("latest") saved tune profile — the JIT/readiness
 * default — was produced: `Heuristic` (analytical), `Card` (model-card
 * sampling), or `Bench` (turbotune-measured). Informational about the
 * active record's origin; NOT a guaranteed selector into `tuned_load` /
 * `benched_load`, because a bare load with edited params demotes the
 * active record to a `Heuristic` distinct from both saved sets (its
 * params ride `last_load`). `None` when the model has no tune record yet.
 */
tune_provenance?: TuneProvenance, 
/**
 * Measured decode throughput (tokens/sec) of the `benched_load` set —
 * the winning turbotune candidate's speed, read from the same saved
 * benchmark record as `benched_load` (NOT from the active profile, so a
 * later bare load editing the active params does not disturb it).
 * Present whenever that record carries a measured throughput; a fresh
 * turbotune replaces it and `benched_load` together. `None` when the
 * model was never benchmarked.
 */
bench_tps?: number, 
/**
 * HuggingFace repo id, `org/model` — the identity used everywhere.
 * Ollama-sourced models keep their established Ollama name (`ollama/{name}:{tag}`);
 * no HuggingFace id is fabricated.
 */
id: string, 
/**
 * Absolute path to the GGUF file.
 */
path: string, 
/**
 * File size in bytes.
 */
size_bytes: number, 
/**
 * Quantization tag parsed from the filename (e.g. `Q4_K_M`), if present.
 */
quant?: string, 
/**
 * Which store the file was found in.
 */
source: HiggsModelSource, 
/**
 * Model architecture read from GGUF header (e.g. `"llama"`, `"gemma3"`).
 * `None` when the header could not be read or the field is absent.
 */
arch?: string, 
/**
 * Training context length (`{arch}.context_length`) from the GGUF header.
 * `None` when the header could not be read or the field is absent.
 */
ctx_train?: number, 
/**
 * Transformer block count (`{arch}.block_count`) from the GGUF header — the
 * number of layers, used by the autotune KV-cache VRAM estimate. `None` when
 * the header could not be read or the field is absent.
 */
block_count?: number, 
/**
 * Attention query-head count (`{arch}.attention.head_count`). Used with
 * `embedding_length` to derive `head_dim` for the KV estimate. `None` when absent.
 */
head_count?: number, 
/**
 * Attention KV/GQA head count (`{arch}.attention.head_count_kv`) — the
 * grouped-query KV head count, which is what sizes the KV cache (NOT the query
 * `head_count`, which over-estimates KV by the GQA factor). `None` when absent.
 */
head_count_kv?: number, 
/**
 * Embedding/hidden size (`{arch}.embedding_length`). With `head_count` gives
 * `head_dim = embedding_length / head_count`. `None` when absent.
 */
embedding_length?: number, 
/**
 * Number of MoE experts (`{arch}.expert_count`); `0`/absent for dense models.
 * Drives the autotune `cpu_moe` back-off decision. `None` when absent.
 */
expert_count?: number, 
/**
 * Whether `tokenizer.chat_template` is present in the GGUF header.
 * `false` when the header could not be read.
 */
has_chat_template: boolean, 
/**
 * Whether the chat template declares tool/function calling. Heuristic: the
 * embedded template references tool calls (`tool_call`/`tools`). `false`
 * when there is no template or it carries no tool markup. `serde(default)`
 * so older scan payloads without the field deserialize as `false`.
 */
supports_tools: boolean, 
/**
 * Whether the model emits a reasoning/thinking block. Heuristic: the
 * template references `<think>`/thinking. `false` when unknown.
 */
supports_reasoning: boolean, 
/**
 * Curated load-relevant GGUF header fields (architecture, quant, tokenizer,
 * block/head counts, gguf version) for the UI to pin a support mismatch to a
 * specific component. Empty when the header could not be read. `serde(default)`
 * so older scan payloads without the field deserialize as empty.
 */
gguf_components: Array<GgufComponent>, };
