// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadParams } from "./LoadParams";

/**
 * Host-supplied configuration (the host maps its own config table onto this).
 */
export type HiggsConfig = { 
/**
 * LM Studio model directories to scan.
 */
lmstudio_dirs: Array<string>, 
/**
 * HuggingFace Hub cache directories to scan.
 *
 * Note: HuggingFace hardcodes `~/.cache/huggingface/hub` on ALL platforms —
 * it does not follow XDG or macOS conventions. We use
 * `dirs::home_dir().join(".cache/huggingface/hub")`, NOT `dirs::cache_dir()`.
 */
hf_dirs: Array<string>, 
/**
 * Ollama model store directories to scan.
 */
ollama_dirs: Array<string>, 
/**
 * Load parameters used when none are supplied by the caller.
 */
default_load: LoadParams, };
