// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `GET /api/higgs/version`.
 */
export type HiggsVersionResponse = { 
/**
 * Higgs crate version from Cargo.toml (`CARGO_PKG_VERSION`).
 */
higgs: string, 
/**
 * Human-readable engine name.
 */
engine: string, 
/**
 * Engine version reported at runtime by `ggml_version()` (e.g. `"0.9.7"`) —
 * the actual vendored ggml/llama.cpp engine version.
 */
engine_version: string, 
/**
 * `llama-cpp-2` Rust binding crate version (e.g. `"0.1.139"`).
 */
binding: string, 
/**
 * File formats this runtime supports.
 */
supported_formats: Array<string>, };
