// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadedInfo } from "./LoadedInfo";
import type { ModelLoading } from "./ModelLoading";

/**
 * Live status snapshot returned by [`Higgs::status`].
 */
export type HiggsStatus = { 
/**
 * Whether the worker process is currently alive.
 */
worker_alive: boolean, 
/**
 * A load currently in flight on the local node (for a progress indicator),
 * or `None` when nothing is loading.
 */
loading?: ModelLoading, 
/**
 * Info about the PRIMARY loaded model (lowest worker id), if any. Kept for the status
 * bar + provider seeding; `loaded_all` carries every resident model.
 */
loaded?: LoadedInfo, 
/**
 * EVERY resident local model — one entry per worker (the local node is multi-model:
 * additive loads, one worker per model), sorted by worker id, `loaded` first. Always an
 * array (empty when nothing is loaded). The UI's "Loaded Models" section renders one card
 * per entry. `#[serde(default)]` keeps deserialization tolerant; clients still default it
 * defensively (`status.loaded_all ?? []`) as cheap insurance.
 */
loaded_all: Array<LoadedInfo>, 
/**
 * Number of models discovered in the last scan.
 */
models_on_disk: number, };
