// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `GET /api/higgs/logs`: `{"lines":[…]}`.
 */
export type HiggsLogsResponse = { 
/**
 * Worker stderr tail, oldest first.
 */
lines: Array<string>, };
