// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `GET /api/higgs/hub`: whether this server is a fleet hub right now.
 *
 * `enabled` is false when hub mode is off (no hub installed) — the Fleet tab shows a
 * "hub mode off" panel instead of inferring it from a `/pair` 409. When enabled, `hub_id`
 * is the hub's stable iroh endpoint id and `node_count` is how many nodes it has admitted
 * (connected or not).
 */
export type HiggsHubStatus = { 
/**
 * True when this server runs as a fleet hub (accepting node dials).
 */
enabled: boolean, 
/**
 * The hub's stable id (iroh endpoint id); `None` when hub mode is off.
 */
hub_id?: string, 
/**
 * Nodes admitted to the fleet (connected or not); 0 when hub mode is off.
 */
node_count: number, };
