// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * `POST /api/higgs/keys` request: mint a key. Omitted `scopes` defaults to
 * `[chat, models]` (the CLI's default) — pass `["admin"]` explicitly for a
 * management key.
 */
export type HiggsMintKeyRequest = { label: string, scopes?: Array<Scope>, };
