// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlashAttn } from "./FlashAttn";
import type { GpuLayers } from "./GpuLayers";
import type { KvCacheKind } from "./KvCacheKind";
import type { LoadParams } from "./LoadParams";

/**
 * Request body for `POST /api/higgs/models/load`.
 *
 * Absent load parameters fall back to the host-configured defaults.
 */
export type HiggsLoadRequest = { 
/**
 * HuggingFace repo id of the model to load.
 */
id: string, 
/**
 * Context window size in tokens.
 */
ctx_len?: number, 
/**
 * GPU layers to offload (`GpuLayers::All` = every layer; `Count { n }` = explicit).
 */
gpu_layers?: GpuLayers, 
/**
 * Worker threads used during generation.
 */
threads?: number, 
/**
 * Memory-map the GGUF instead of reading it into RAM.
 */
use_mmap?: boolean, 
/**
 * Lock model pages in RAM (prevent swap).
 */
use_mlock?: boolean, 
/**
 * Logical batch size for prompt decode.
 */
n_batch?: number, 
/**
 * Physical (micro) batch size.
 */
n_ubatch?: number, 
/**
 * Offload the KV cache & KQV ops to the GPU.
 */
offload_kqv?: boolean, 
/**
 * RoPE base frequency override.
 */
rope_freq_base?: number, 
/**
 * RoPE frequency scale (context extension).
 */
rope_freq_scale?: number, 
/**
 * Flash-attention policy.
 */
flash_attn?: FlashAttn, 
/**
 * KV cache key data type.
 */
type_k?: KvCacheKind, 
/**
 * KV cache value data type.
 */
type_v?: KvCacheKind, 
/**
 * Sampler RNG seed for reproducible generation.
 */
seed?: number, 
/**
 * Per-load idle-TTL override in minutes. RESERVED / forward-compat: per-load
 * idle-TTL enforcement is a deferred follow-up, so this is currently ACCEPTED
 * but NOT enforced — the node reaper applies one per-node TTL to every worker
 * (the global TTL, `/api/higgs/settings`), and the host neither stores nor
 * surfaces this value. It will take effect once the reaper honors per-worker
 * overrides (host-side only either way — never forwarded to the worker/engine).
 */
idle_ttl_minutes?: number, 
/**
 * The FULL engine load params, as the engine-tagged [`LoadParams`] umbrella
 * (`{"engine":"LlamaCpp", …}`) — an accepted autotune suggestion or a manual
 * edit of the complete §4/§5 surface. When present it SUPERSEDES the flat
 * fields above (kept for back-compat); its base fields are used as-is. This
 * is what the frontend sends after `[Tune params]` fills the pane — and the
 * engine tag means a future MLX engine sends `{"engine":"Mlx", …}` here
 * without a new wire field.
 */
params?: LoadParams, };
