// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `logs` control-op response — the worker log tail (formerly
 * `GET /api/higgs/logs`): `{"lines":[…]}`. The live stream now rides the
 * `/ws` watch_logs subscription, not this batched tail.
 */
export type HiggsLogsResponse = { 
/**
 * Worker stderr tail, oldest first.
 */
lines: Array<string>, };
