// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * One configured API key as the management surface lists it: label,
 * scopes, and a short digest prefix as its display identifier. NEVER the
 * plaintext token (shown once at mint) and never the full digest.
 */
export type HiggsKeyEntry = { label: string, scopes: Array<Scope>, 
/**
 * First 12 hex chars of the stored SHA-256 digest.
 */
sha256_prefix: string, 
/**
 * Unix-ms the key was minted; `None` for keys from a pre-timestamp
 * store (render as unknown).
 */
created_at_ms?: number, 
/**
 * Unix-ms of the last successful authorization, `None` if never used.
 * Served from the LIVE store (lags at most the ~1-min touch throttle).
 * Usage is best-effort history: it reaches disk only when a later
 * mint/revoke persists the store, so a restart shows the stamps as of
 * that last mutation ("never" if none since).
 */
last_used_ms?: number, };
