// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const HiggsModelSource = {
    LmStudio : "LmStudio",
    HfCache  : "HfCache",
    Ollama   : "Ollama",
} as const;

export const { LmStudio, HfCache, Ollama } = HiggsModelSource;

export type HiggsModelSource = (typeof HiggsModelSource)[keyof typeof HiggsModelSource];
