// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GgufComponent } from "./GgufComponent";
import type { HiggsModelSource } from "./HiggsModelSource";

/**
 * One discoverable model file on disk.
 */
export type HiggsModel = { 
/**
 * HuggingFace repo id, `org/model` — the identity used everywhere.
 * Ollama-sourced models keep their established Ollama name (`ollama/{name}:{tag}`);
 * no HuggingFace id is fabricated.
 */
id: string, 
/**
 * Absolute path to the GGUF file.
 */
path: string, 
/**
 * File size in bytes.
 */
size_bytes: number, 
/**
 * Quantization tag parsed from the filename (e.g. `Q4_K_M`), if present.
 */
quant?: string, 
/**
 * Which store the file was found in.
 */
source: HiggsModelSource, 
/**
 * Model architecture read from GGUF header (e.g. `"llama"`, `"gemma3"`).
 * `None` when the header could not be read or the field is absent.
 */
arch?: string, 
/**
 * Training context length (`{arch}.context_length`) from the GGUF header.
 * `None` when the header could not be read or the field is absent.
 */
ctx_train?: number, 
/**
 * Transformer block count (`{arch}.block_count`) from the GGUF header — the
 * number of layers, used by the autotune KV-cache VRAM estimate. `None` when
 * the header could not be read or the field is absent.
 */
block_count?: number, 
/**
 * Attention query-head count (`{arch}.attention.head_count`). Used with
 * `embedding_length` to derive `head_dim` for the KV estimate. `None` when absent.
 */
head_count?: number, 
/**
 * Attention KV/GQA head count (`{arch}.attention.head_count_kv`) — the
 * grouped-query KV head count, which is what sizes the KV cache (NOT the query
 * `head_count`, which over-estimates KV by the GQA factor). `None` when absent.
 */
head_count_kv?: number, 
/**
 * Embedding/hidden size (`{arch}.embedding_length`). With `head_count` gives
 * `head_dim = embedding_length / head_count`. `None` when absent.
 */
embedding_length?: number, 
/**
 * Number of MoE experts (`{arch}.expert_count`); `0`/absent for dense models.
 * Drives the autotune `cpu_moe` back-off decision. `None` when absent.
 */
expert_count?: number, 
/**
 * Whether `tokenizer.chat_template` is present in the GGUF header.
 * `false` when the header could not be read.
 */
has_chat_template: boolean, 
/**
 * Whether the chat template declares tool/function calling. Heuristic: the
 * embedded template references tool calls (`tool_call`/`tools`). `false`
 * when there is no template or it carries no tool markup. `serde(default)`
 * so older scan payloads without the field deserialize as `false`.
 */
supports_tools: boolean, 
/**
 * Whether the model emits a reasoning/thinking block. Heuristic: the
 * template references `<think>`/thinking. `false` when unknown.
 */
supports_reasoning: boolean, 
/**
 * Curated load-relevant GGUF header fields (architecture, quant, tokenizer,
 * block/head counts, gguf version) for the UI to pin a support mismatch to a
 * specific component. Empty when the header could not be read. `serde(default)`
 * so older scan payloads without the field deserialize as empty.
 */
gguf_components: Array<GgufComponent>, };
