// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One resident worker in a node's [`NodeInventory`]: its node-local id and the model it
 * currently serves.
 */
export type InventoryWorker = { worker_id: number, model: string, };
