// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuLayers } from "./GpuLayers";
import type { HiggsModel } from "./HiggsModel";
import type { ModelDomain } from "./ModelDomain";

/**
 * One resident worker in a node's [`NodeInventory`]: its node-local id and the model it
 * currently serves, plus the hub-assigned `/v1` served id.
 *
 * `PartialEq`/`Eq` intentionally dropped when the `model_info` field was added: `HiggsModel`
 * carries a `Vec<GgufComponent>` and other nested types not required to be structurally
 * comparable, and no callsite actually compared whole `InventoryWorker` values (field-level
 * asserts throughout). Removing the derives keeps `Option<HiggsModel>` embeddable without
 * forcing `PartialEq` down the whole scan-model tree.
 */
export type InventoryWorker = { worker_id: number, model: string, 
/**
 * The collision-free `/v1` served instance id clients call to reach THIS worker
 * (`org/model`, `org/model-1`, …). This is a HUB concept derived from the routing
 * table — the node does not know it, so `M_NODE_INVENTORY` payloads omit it
 * (`serde(default)` → empty) and the hub fills it in [`crate::node::fleet`]'s
 * `nodes_view`. Empty for a resident worker the hub holds no route for.
 */
served_id: string, 
/**
 * The EFFECTIVE context window the worker was loaded with — the crate's
 * OPERATIVE window: the value the load pinned (explicit param, else
 * trained-cap default, else the worker's own fallback; `node/runtime.rs`
 * `effective_ctx`) and the one every fit-check enforces. llama.cpp may
 * pad its internal allocation upward (`n_ctx` to a 256 multiple) — the
 * pad is unobservable through any higgs surface. From the node's
 * load-time cache: no RPC to a possibly-busy worker. Absent ONLY from
 * pre-stats nodes (`serde(default)` — additive, no protocol bump); a
 * current node always knows it.
 */
ctx_len?: number, 
/**
 * GPU offload the load requested (absent = the worker default, all).
 */
gpu_layers?: GpuLayers, 
/**
 * The worker's capability class, captured at LOAD time on the node
 * (`LoadFacts.domain`). The hub reads it to keep non-generative remote
 * workers out of the `/v1/models` chat union — the node's own `ChatHandle`
 * [HG079] gate stays the enforcement. `serde(default)` = `Llm`: an OLDER
 * node never reports it, and the hub deliberately stays permissive about
 * what it cannot see (additive, no protocol bump).
 */
domain: ModelDomain, 
/**
 * Generation threads the load requested (absent = the worker default).
 */
threads?: number, 
/**
 * Wall-clock ms (Unix epoch) when this worker id FIRST loaded its model.
 * A crash-respawn (the Supervisor restart FSM replaying the load) keeps
 * the original stamp — "when did this worker come up", not "when did the
 * child process last restart". `ts(type = "number")` like every other
 * wire u64 (`system.rs`): the JSON value is a number, and epoch ms sit
 * far below 2^53.
 */
loaded_at_ms?: number, 
/**
 * Milliseconds since the worker's last chat activity, measured at
 * snapshot time (the idle reaper's own clock). Freshness is
 * event-driven: the hub re-pulls inventory on connect and after
 * lifecycle ops, so this ages between pulls. `ts(type = "number")` as
 * above.
 */
idle_ms?: number, 
/**
 * Chats in flight on this worker at snapshot time.
 */
in_flight?: number, 
/**
 * The full scan-cache view of the model this worker is serving — the same
 * `HiggsModel` a LOCAL client sees via the models catalog, so a remote
 * worker's row can render quant / arch / ctx_train / block+head counts /
 * gguf_components / has_chat_template / supports_tools / supports_reasoning
 * / enrich_error / source WITHOUT the hub second-guessing (or the flat
 * `InventoryWorker` fields drifting from `HiggsModel` as it grows).
 *
 * Snapshotted onto `LoadFacts` when the load resolved the file, so a
 * concurrent rescan / delete / re-download after load cannot mutate what
 * this worker's row reports about the file it actually loaded. `None`
 * only from a pre-r-N node that didn't send it (`serde(default)`, additive).
 * `HiggsModel.chat_template` is `serde(skip)` so the multi-KB template
 * stays host-only; `HiggsModel.path` DOES ride (it is not `serde(skip)`)
 * and the hub treats it as a node-local string — visible for diagnostics,
 * meaningless to open on any other host.
 */
model_info?: HiggsModel, };
