// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * KV-cache element type (the LM Studio subset of GGML types usable for the
 * K/V cache). Engine-agnostic here; mapped to `llama_cpp_2`'s `KvCacheType`
 * only inside `llamacpp.rs`.
 */
export type KvCacheKind = "F32" | "F16" | "Q8_0" | "Q5_1" | "Q5_0" | "Q4_1" | "Q4_0";
