// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const KvCacheKind = {
    F32  : "F32",
    F16  : "F16",
    Q8_0 : "Q8_0",
    Q5_1 : "Q5_1",
    Q5_0 : "Q5_0",
    Q4_1 : "Q4_1",
    Q4_0 : "Q4_0",
} as const;

export const { F32, F16, Q8_0, Q5_1, Q5_0, Q4_1, Q4_0 } = KvCacheKind;

export type KvCacheKind = (typeof KvCacheKind)[keyof typeof KvCacheKind];
