// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GGUF metadata override applied at load via `append_kv_override` (advanced
 * / manual). `value` is the textual form llama.cpp parses per the key's type.
 */
export type KvOverride = { 
/**
 * GGUF metadata key, e.g. `llama.context_length`.
 */
key: string, 
/**
 * Override value as a string (llama.cpp coerces by the key's declared type).
 */
value: string, };
