// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const LinkPath = {
    Direct : "direct",
    Relay  : "relay",
} as const;

export const { Direct, Relay } = LinkPath;

export type LinkPath = (typeof LinkPath)[keyof typeof LinkPath];
