// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const LinkState = {
    Healthy      : "healthy",
    Degraded     : "degraded",
    Disconnected : "disconnected",
} as const;

export const { Healthy, Degraded, Disconnected } = LinkState;

export type LinkState = (typeof LinkState)[keyof typeof LinkState];
