// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Per-field help via `#[derive(TsParamHelp)]` in `higgs-macros`.

export const LlamaCppParamsHelp = {
    "ctx_len": "context window size",
    "gpu_layers": "layers offloaded to GPU",
    "threads": "generation threads",
    "use_mmap": "memory-map the model file",
    "use_mlock": "lock model in RAM",
    "cpu_moe": "keep MoE experts on CPU",
    "cpu_buft_overrides": "CPU tensor-buffer overrides",
    "split_mode": "multi-GPU split mode",
    "main_gpu": "primary GPU index",
    "devices": "explicit GPU devices",
    "n_batch": "prompt batch size",
    "n_ubatch": "physical micro-batch size",
    "n_seq_max": "parallel sequence slots",
    "n_threads_batch": "prompt-processing threads",
    "flash_attn": "flash-attention policy",
    "offload_kqv": "KV cache on GPU",
    "swa_full": "full sliding-window attention",
    "type_k": "KV key cache type",
    "type_v": "KV value cache type",
    "rope_scaling_type": "RoPE scaling mode",
    "rope_freq_base": "RoPE base frequency",
    "rope_freq_scale": "RoPE frequency scale",
    "kv_overrides": "GGUF metadata overrides",
    "seed": "sampler RNG seed",
} as const;

export type LlamaCppParamsHelpKey = keyof typeof LlamaCppParamsHelp;
