// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DryParams } from "./DryParams";
import type { GrammarParams } from "./GrammarParams";
import type { LogitBias } from "./LogitBias";
import type { MirostatParams } from "./MirostatParams";

/**
 * Full llama.cpp sampler parameters — the `LlamaCpp` payload of the
 * [`crate::worker::engine::SamplingParams`] umbrella. Every sampler the
 * 0.1.139 bindings expose is representable (DESIGN §4c); `None` ⇒ omit that
 * sampler from the chain. The chain order is fixed in `llamacpp/mod.rs`. The
 * suggester only ever auto-fills the common ones (temp/top_k/top_p/min_p/
 * penalties from the HF card); the rest are user-settable but never derived.
 */
export type LlamaCppSamplingParams = { 
/**
 * Sampling temperature (`temp`). `<= 0` ⇒ greedy.
 */
temperature?: number, 
/**
 * Dynamic-temperature range (`temp_ext`); pairs with `dynatemp_exponent`.
 */
dynatemp_range?: number, 
/**
 * Dynamic-temperature exponent (`temp_ext`).
 */
dynatemp_exponent?: number, 
/**
 * Top-k cutoff (`top_k`).
 */
top_k?: number, 
/**
 * Top-p / nucleus cutoff (`top_p`, with `min_keep = 1`).
 */
top_p?: number, 
/**
 * Min-p cutoff (`min_p`, with `min_keep = 1`).
 */
min_p?: number, 
/**
 * Locally-typical-p cutoff (`typical`, with `min_keep = 1`).
 */
typical_p?: number, 
/**
 * Top-n-sigma cutoff (`top_n_sigma`).
 */
top_n_sigma?: number, 
/**
 * XTC probability (`xtc`); pairs with `xtc_threshold`.
 */
xtc_probability?: number, 
/**
 * XTC threshold (`xtc`).
 */
xtc_threshold?: number, 
/**
 * Repetition-penalty window (`penalties` `last_n`).
 */
penalty_last_n?: number, 
/**
 * Repetition penalty (`penalties` `repeat`).
 */
penalty_repeat?: number, 
/**
 * Frequency penalty (`penalties` `freq`).
 */
penalty_freq?: number, 
/**
 * Presence penalty (`penalties` `present`).
 */
penalty_present?: number, 
/**
 * DRY repetition sampler (`dry`).
 */
dry?: DryParams, 
/**
 * Mirostat adaptive sampler (`mirostat`/`mirostat_v2`).
 */
mirostat?: MirostatParams, 
/**
 * Per-token logit biases (`logit_bias`). Always serialized (possibly `[]`)
 * — honest required-array binding.
 */
logit_bias: Array<LogitBias>, 
/**
 * GBNF grammar constraint (`grammar`).
 */
grammar?: GrammarParams, 
/**
 * Per-request sampler RNG seed (`dist`); overrides the load-pinned seed.
 */
seed?: number, };
