// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtxLen } from "./CtxLen";
import type { FlashAttn } from "./FlashAttn";
import type { GpuLayers } from "./GpuLayers";
import type { KvCacheKind } from "./KvCacheKind";
import type { KvOverride } from "./KvOverride";
import type { RopeScalingType } from "./RopeScalingType";
import type { SplitMode } from "./SplitMode";

/**
 * Full llama.cpp load parameters — the `LlamaCpp` payload of the
 * [`crate::worker::engine::LoadParams`] umbrella. Covers every model+context
 * knob the `llama-cpp-2` 0.1.139 bindings expose (DESIGN §4a/§4b). The three
 * base fields (`ctx_len`/`gpu_layers`/`threads`) are always present — the
 * quick-load / `default_load` / suggester path fills them; "all on GPU" is
 * the typed `GpuLayers::All` (the old `u32::MAX` sentinel is gone). Every other field
 * is optional: absent (`None`/empty) means "use the engine default", which
 * reproduces the pre-expansion behavior exactly.
 */
export type LlamaCppParams = { 
/**
 * Context window (`with_n_ctx`). [`CtxLen::Auto`] = the engine's trained context
 * (the old `ctx_len == 0` sentinel); [`CtxLen::Fixed`] pins an explicit window.
 */
ctx_len: CtxLen, 
/**
 * Layers offloaded to GPU (`with_n_gpu_layers`). [`GpuLayers::All`] = every layer
 * (the old `u32::MAX` sentinel); [`GpuLayers::Count`] carries an explicit count.
 */
gpu_layers: GpuLayers, 
/**
 * Worker threads used during generation (`with_n_threads`; also seeds
 * `n_threads_batch` when that is unset).
 */
threads: number, 
/**
 * Memory-map the GGUF instead of reading it into RAM (`with_use_mmap`).
 */
use_mmap?: boolean, 
/**
 * Lock model pages in RAM, preventing swap (`with_use_mlock`).
 */
use_mlock?: boolean, 
/**
 * Keep MoE expert tensors on the CPU (`add_cpu_moe_override`, pinned
 * apply). Boolean only — no numeric `n_cpu_moe` binding exists. The
 * suggester flips this on under VRAM pressure when RAM still fits.
 */
cpu_moe?: boolean, 
/**
 * Per-tensor-buffer-type → CPU regex overrides (`add_cpu_buft_override`,
 * pinned apply; advanced/manual). Drives finer MoE offload later. Always
 * serialized (possibly `[]`) so the bindings' required-array shape is honest.
 */
cpu_buft_overrides: Array<string>, 
/**
 * Multi-GPU split mode (`with_split_mode`). DEFERRED-derive; no-op default.
 */
split_mode?: SplitMode, 
/**
 * Primary GPU index when `split_mode = None` (`with_main_gpu`). DEFERRED.
 */
main_gpu?: number, 
/**
 * Explicit device selection (`with_devices`). DEFERRED (multi-GPU). Wire
 * type is `u32` (ts-portable); the apply path converts to `usize`.
 */
devices?: Array<number>, 
/**
 * Logical batch size for prompt decode (`with_n_batch`). `None` keeps the
 * current default (`ctx_len.max(1)` — one-shot prefill).
 */
n_batch?: number, 
/**
 * Physical (micro) batch size (`with_n_ubatch`).
 */
n_ubatch?: number, 
/**
 * Parallel sequence slots (`with_n_seq_max`); default 1.
 */
n_seq_max?: number, 
/**
 * Threads for batch/prompt processing (`with_n_threads_batch`). `None`
 * reuses `threads` (today's shared behavior).
 */
n_threads_batch?: number, 
/**
 * Flash-attention policy (`with_flash_attention_policy`).
 */
flash_attn?: FlashAttn, 
/**
 * Offload the KV cache & KQV ops to the GPU (`with_offload_kqv`).
 */
offload_kqv?: boolean, 
/**
 * Full sliding-window attention (`with_swa_full`).
 */
swa_full?: boolean, 
/**
 * KV cache key data type (`with_type_k`).
 */
type_k?: KvCacheKind, 
/**
 * KV cache value data type (`with_type_v`).
 */
type_v?: KvCacheKind, 
/**
 * RoPE scaling type (`with_rope_scaling_type`).
 */
rope_scaling_type?: RopeScalingType, 
/**
 * RoPE base frequency override (`with_rope_freq_base`).
 */
rope_freq_base?: number, 
/**
 * RoPE frequency scale / context extension (`with_rope_freq_scale`).
 */
rope_freq_scale?: number, 
/**
 * GGUF metadata overrides (`append_kv_override`, pinned apply; advanced).
 * Always serialized (possibly `[]`) — honest required-array binding.
 */
kv_overrides: Array<KvOverride>, 
/**
 * Load-pinned sampler RNG seed. `None` = a fresh random seed per request.
 * A per-request `LlamaCppSamplingParams::seed` overrides this when set.
 */
seed?: number, };
