// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about the currently loaded model.
 */
export type LoadedInfo = { 
/**
 * HuggingFace repo id of the resident model.
 */
id: string, 
/**
 * Context window size in tokens.
 */
ctx_len: number, 
/**
 * GPU layers offloaded; u32::MAX means all.
 */
gpu_layers: number, 
/**
 * Worker threads used during generation.
 */
threads: number, 
/**
 * Model architecture read from GGUF header (e.g. `"llama"`, `"gemma3"`).
 */
arch?: string, 
/**
 * Quantization tag (e.g. `Q4_K_M`), if present.
 */
quant?: string, 
/**
 * Training context length from GGUF header (model's maximum). Distinct from
 * `ctx_len` which is the actually loaded window size.
 */
max_context_length?: number, 
/**
 * File size in bytes.
 */
size_bytes?: number, 
/**
 * Whether `tokenizer.chat_template` is present in the GGUF header.
 */
has_chat_template?: boolean, 
/**
 * Active per-load idle-TTL override in minutes, if one was set at load
 * time. Absent when the loaded model uses the global idle TTL.
 */
idle_ttl_minutes?: number, };
