// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about the currently loaded model.
 */
export type LoadedInfo = { 
/**
 * HuggingFace repo id of the resident model.
 */
id: string, 
/**
 * The node-local worker id serving this model. Distinguishes the entries of
 * [`HiggsStatus::loaded_all`] (one worker per resident model) so the UI can key a
 * per-worker card + its per-worker log pane. Always present.
 */
worker_id: number, 
/**
 * Context window size in tokens.
 */
ctx_len: number, 
/**
 * GPU layers offloaded; u32::MAX means all.
 */
gpu_layers: number, 
/**
 * Worker threads used during generation.
 */
threads: number, 
/**
 * Model architecture read from GGUF header (e.g. `"llama"`, `"gemma3"`).
 */
arch?: string, 
/**
 * Quantization tag (e.g. `Q4_K_M`), if present.
 */
quant?: string, 
/**
 * Training context length from GGUF header (model's maximum). Distinct from
 * `ctx_len` which is the actually loaded window size.
 */
max_context_length?: number, 
/**
 * File size in bytes.
 */
size_bytes?: number, 
/**
 * Whether `tokenizer.chat_template` is present in the GGUF header.
 */
has_chat_template?: boolean, 
/**
 * Per-load idle-TTL override in minutes. RESERVED: per-load idle-TTL
 * enforcement is a deferred follow-up (the node reaper applies one per-node
 * TTL to every worker), so this is currently ALWAYS absent — every loaded
 * model uses the global idle TTL (`/api/higgs/settings`). It becomes
 * populated only once the reaper honors per-worker overrides.
 */
idle_ttl_minutes?: number, };
