// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlamaCppParams } from "./LlamaCppParams";

/**
 * Engine-tagged **load-parameter umbrella**. `LoadParams::LlamaCpp(LlamaCppParams)`
 * today; a future `Mlx(MlxParams)` slots beside it. "All are `LoadParams`."
 *
 * Serialized **internally tagged** on the `engine` field, so the JSON is the
 * flattened llama.cpp payload plus `"engine":"LlamaCpp"`. The worker dispatches
 * on the variant; the suggester (`src/tune/`) derives the concrete payload.
 * The concrete fields live in [`llamacpp::params::LlamaCppParams`] (full
 * `llama-cpp-2` 0.1.139 coverage) — applied only inside `llamacpp/mod.rs`.
 */
export type LoadParams = { "engine": "LlamaCpp" } & LlamaCppParams;
