// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlashAttn } from "./FlashAttn";
import type { KvCacheKind } from "./KvCacheKind";

/**
 * Parameters fixed at load time.
 *
 * The three base fields (`ctx_len`/`gpu_layers`/`threads`) are always
 * present — the quick-load / `default_load` path fills them. Every other
 * field is `Option`: absent (`None`) means "use the engine default", which
 * reproduces the pre-expansion behavior exactly. Each optional maps to a
 * real `llama-cpp-2` 0.1.139 builder call, applied only inside `llamacpp.rs`
 * (the sole file allowed to name `llama_cpp_2`).
 */
export type LoadParams = { ctx_len: number, 
/**
 * Layers offloaded to GPU; u32::MAX = all (LM Studio "max" semantics).
 */
gpu_layers: number, threads: number, 
/**
 * Memory-map the GGUF instead of reading it into RAM. `None` = engine
 * default. Applied via `LlamaModelParams::with_use_mmap`.
 */
use_mmap?: boolean, 
/**
 * Lock model pages in RAM (prevent swap). `None` = engine default.
 * Applied via `LlamaModelParams::with_use_mlock`.
 */
use_mlock?: boolean, 
/**
 * Logical batch size for prompt decode. `None` keeps the current
 * default (`ctx_len.max(1)` — one-shot prefill). Applied via
 * `LlamaContextParams::with_n_batch`.
 */
n_batch?: number, 
/**
 * Physical (micro) batch size. `None` = engine default. Applied via
 * `LlamaContextParams::with_n_ubatch`.
 */
n_ubatch?: number, 
/**
 * Offload the KV cache & KQV ops to the GPU. `None` = engine default.
 * Applied via `LlamaContextParams::with_offload_kqv`.
 */
offload_kqv?: boolean, 
/**
 * RoPE base frequency override. `None` = use the GGUF's trained value.
 * Applied via `LlamaContextParams::with_rope_freq_base`.
 */
rope_freq_base?: number, 
/**
 * RoPE frequency scale (context extension). `None` = trained value.
 * Applied via `LlamaContextParams::with_rope_freq_scale`.
 */
rope_freq_scale?: number, 
/**
 * Flash-attention policy. `None` = engine default. Applied via
 * `LlamaContextParams::with_flash_attention_policy`.
 */
flash_attn?: FlashAttn, 
/**
 * KV cache key data type. `None` = engine default (F16). Applied via
 * `LlamaContextParams::with_type_k`.
 */
type_k?: KvCacheKind, 
/**
 * KV cache value data type. `None` = engine default (F16). Applied via
 * `LlamaContextParams::with_type_v`.
 */
type_v?: KvCacheKind, 
/**
 * Sampler RNG seed. `None` keeps the current behavior: a fresh random
 * seed per request (`LlamaSampler::dist(rand::random())`). When set,
 * generation is reproducible. Greedy decoding (temperature 0) ignores it.
 */
seed?: number, };
