// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtxLen } from "./CtxLen";
import type { GpuLayers } from "./GpuLayers";

/**
 * Info about the currently loaded model.
 */
export type LoadedInfo = { 
/**
 * HuggingFace repo id of the resident model.
 */
id: string, 
/**
 * The node-local worker id serving this model. Distinguishes the entries of
 * [`HiggsStatus::loaded_all`] (one worker per resident model) so the UI can key a
 * per-worker card + its per-worker log pane. Always present.
 */
worker_id: number, 
/**
 * Context window of the LIVE worker ([`CtxLen::Auto`] = trained context; `Fixed { n }`
 * = pinned). `None` = NOT PROBED — the worker is busy mid-generation and couldn't
 * answer the status probe; the card still shows (resident) but the live window is
 * unknown (was the dishonest `0`/`u32::MAX` placeholder).
 */
ctx_len?: CtxLen, 
/**
 * GPU layers offloaded by the LIVE worker (`GpuLayers::All` / `Count { n }`).
 * `None` = not probed (see `ctx_len`).
 */
gpu_layers?: GpuLayers, 
/**
 * Worker threads of the LIVE worker. `None` = not probed (see `ctx_len`).
 */
threads?: number, 
/**
 * Model architecture read from GGUF header (e.g. `"llama"`, `"gemma3"`).
 */
arch?: string, 
/**
 * Quantization tag (e.g. `Q4_K_M`), if present.
 */
quant?: string, 
/**
 * Training context length from GGUF header (model's maximum). Distinct from
 * `ctx_len` which is the actually loaded window size.
 */
max_context_length?: number, 
/**
 * File size in bytes.
 */
size_bytes?: number, 
/**
 * Whether `tokenizer.chat_template` is present in the GGUF header.
 */
has_chat_template?: boolean, 
/**
 * Per-load idle-TTL override in minutes. RESERVED: per-load idle-TTL
 * enforcement is a deferred follow-up (the node reaper applies one per-node
 * TTL to every worker), so this is currently ALWAYS absent — every loaded
 * model uses the global idle TTL (`HiggsRuntimeSettings`). It becomes
 * populated only once the reaper honors per-worker overrides.
 */
idle_ttl_minutes?: number, };
