// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single logit bias: shift `token`'s logit by `bias` before sampling.
 */
export type LogitBias = { 
/**
 * Vocabulary token id.
 */
token: number, 
/**
 * Additive logit bias (negative discourages, positive encourages).
 */
bias: number, };
