// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `GET`/`PUT /api/higgs/logs/settings`: the runtime Developer-Log
 * toggles. `GET` returns the current state of both; `PUT` carries both and
 * sets both. The log settings higgs actually backs.
 */
export type LogSettings = { 
/**
 * Whether the serve-layer verbose serving line is enabled — when `true`,
 * the chat path emits an extra `higgs: served …` completion line per
 * request into the Developer Logs.
 */
verbose: boolean, 
/**
 * Whether the serve-layer incoming-prompt line is enabled — when `true`,
 * the chat path emits a `higgs: incoming …` line carrying the (capped)
 * prompt CONTENT per request. This is the explicit opt-in that overrides
 * the redact-by-default policy; default `false`.
 */
log_incoming_tokens: boolean, 
/**
 * DEBUG: when `true`, the Developer-Log layer also emits non-message
 * structured fields — INCLUDING prompt CONTENT — un-redacting the logs
 * for debugging. Off by default. `#[serde(default)]` so older PUT bodies
 * that omit it deserialize as `false`.
 */
show_log_fields: boolean, };
