// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirostat adaptive-perplexity sampler parameters. `version` selects
 * `mirostat` (1) vs `mirostat_v2` (2); the v1 `m` scalar is fixed to
 * llama.cpp's default (100) and not exposed.
 */
export type MirostatParams = { 
/**
 * Algorithm version: `1` or `2`.
 */
version: number, 
/**
 * Target entropy (tau).
 */
tau: number, 
/**
 * Learning rate (eta).
 */
eta: number, };
