// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelReadiness = "discovered" | "profiled" | "servable" | "unservable" | "needs_retune" | "loaded";
