// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The analytical resource fit for a model's saved profile against the node's
 * CURRENT free resources — the numbers behind the `Servable`/`Unservable`
 * badge, so the UI can say "≈22 GB needed, 18 GB free" instead of a bare
 * verdict. Present only when a profile was actually evaluated for fit
 * (i.e. the model is `servable` or `unservable`); `None` otherwise.
 *
 * ADVISORY: `free_*` come from the cached device snapshot (a live refresh
 * would spawn a sysinfo worker per poll), so render the figures as "≈".
 */
export type ModelFit = { 
/**
 * Estimated VRAM the profile needs to load + serve.
 */
needed_vram_bytes: number, 
/**
 * Estimated system RAM the profile needs.
 */
needed_ram_bytes: number, 
/**
 * GPU free VRAM at the last device snapshot.
 */
free_vram_bytes: number, 
/**
 * System free RAM at the last device snapshot.
 */
free_ram_bytes: number, };
