// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const ModelReadiness = {
    Discovered  : "discovered",
    Profiled    : "profiled",
    Servable    : "servable",
    Unservable  : "unservable",
    NeedsRetune : "needs_retune",
    Loaded      : "loaded",
} as const;

export const { Discovered, Profiled, Servable, Unservable, NeedsRetune, Loaded } = ModelReadiness;

export type ModelReadiness = (typeof ModelReadiness)[keyof typeof ModelReadiness];
