// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const ModelLoadPhase = {
    Queued         : "queued",
    Preparing      : "preparing",
    LoadingWeights : "loading_weights",
    Finalizing     : "finalizing",
    Ready          : "ready",
    Failed         : "failed",
} as const;

export const { Queued, Preparing, LoadingWeights, Finalizing, Ready, Failed } = ModelLoadPhase;

export type ModelLoadPhase = (typeof ModelLoadPhase)[keyof typeof ModelLoadPhase];
