// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDownloadPhase } from "./ModelDownloadPhase";

/**
 * A live catalog-download progress event, delivered over
 * [`Higgs::subscribe_download_events`](crate::api::Higgs::subscribe_download_events).
 * Progress events are throttled by the emitter; terminal phases always
 * emit.
 */
export type ModelDownloadEvent = { 
/**
 * Fleet node the download runs ON (`Higgs::model_download_on`);
 * absent = this machine (`Higgs::model_download`). One event stream
 * serves every target — subscribers key progress by
 * `(node, repo, file)`.
 */
node?: string, 
/**
 * Hub repo id (`org/model`) being downloaded.
 */
repo: string, 
/**
 * File name inside the repo.
 */
file: string, 
/**
 * The phase this event announces.
 */
phase: ModelDownloadPhase, 
/**
 * Bytes received so far.
 */
downloaded_bytes: number, 
/**
 * Total bytes, when the transfer reported a length.
 */
total_bytes?: number, 
/**
 * Unix-ms when the event was emitted.
 */
at_ms: number, 
/**
 * The `HGxxx` diagnostic code — present only on
 * [`ModelDownloadPhase::Failed`].
 */
code?: string, 
/**
 * Final on-disk path — present only on [`ModelDownloadPhase::Done`].
 */
path?: string, };
