// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model load currently IN FLIGHT on the local node — surfaced so the UI can
 * show a progress indicator during the (multi-second) load instead of a silent
 * wait. Present on [`HiggsStatus`] only while a `load` is running; cleared on
 * completion (success or failure).
 */
export type ModelLoading = { 
/**
 * Repo id of the model being loaded.
 */
id: string, 
/**
 * Unix-ms when the load began — the UI animates a progress bar from here
 * against its own size-based estimate (it already has the model's size).
 */
started_ms: number, };
