// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelLoadPhase } from "./ModelLoadPhase";

/**
 * A live model-load lifecycle event, streamed over `GET /api/higgs/events`
 * (SSE). One is pushed at every [`ModelLoadPhase`] transition of a load, so the
 * UI shows/updates/hides the loading indicator from PUSH events instead of
 * polling `status`. Terminal phases (`Ready`/`Failed`) close out the bar;
 * `Failed` carries the diagnostic `code`.
 */
export type ModelLoadEvent = { 
/**
 * Repo id of the model being loaded.
 */
id: string, 
/**
 * The phase this event announces.
 */
phase: ModelLoadPhase, 
/**
 * Unix-ms when the phase was entered.
 */
at_ms: number, 
/**
 * The `HGxxx` diagnostic code — present only on [`ModelLoadPhase::Failed`].
 */
code?: string, };
