// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle phase of an in-flight model load, pushed as a live
 * [`ModelLoadEvent`] over `GET /api/higgs/events` (SSE) at each real seam in
 * [`Higgs::load`](crate::api::Higgs::load) so the UI can show WHAT the load is
 * doing — not just a spinner. Every variant maps to an observable transition in
 * `load_inner`; no phase is faked. `Queued`/`Preparing`/`LoadingWeights`/
 * `Finalizing` are progress phases; `Ready`/`Failed` are terminal.
 */
export type ModelLoadPhase = "queued" | "preparing" | "loading_weights" | "finalizing" | "ready" | "failed";
