// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const ModelDownloadPhase = {
    Starting    : "starting",
    Downloading : "downloading",
    Done        : "done",
    Failed      : "failed",
} as const;

export const { Starting, Downloading, Done, Failed } = ModelDownloadPhase;

export type ModelDownloadPhase = (typeof ModelDownloadPhase)[keyof typeof ModelDownloadPhase];
