// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const ModelDomain = {
    Llm       : "llm",
    Embedding : "embedding",
    Reranker  : "reranker",
} as const;

export const { Llm, Embedding, Reranker } = ModelDomain;

export type ModelDomain = (typeof ModelDomain)[keyof typeof ModelDomain];
