// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkPath } from "./LinkPath";
import type { LinkState } from "./LinkState";

/**
 * One passive snapshot of a node's iroh connection stats + the inferred label.
 * Sampled ON DEMAND when the UI asks (`Higgs::network_stats`); nothing cached,
 * no subscription, no probe traffic. Every field is read from ONE
 * `Path::stats()` snapshot of iroh's currently-selected path (rtt included);
 * numeric fields are serialized as JSON `number`.
 *
 * `lost_packets` / `sent_datagrams` / `bytes_tx` / `bytes_rx` come from
 * `Path::stats()` on the SELECTED path only — they are per-path counters,
 * NOT per-connection totals and NOT per-interval deltas. On a path change
 * the numbers you see are whatever that other path's independent counters
 * have accumulated since its own PathId came into existence (which for
 * direct + relay may date back to connection setup). Consumers wanting
 * rates must diff two samples themselves.
 *
 * No clean loss-rate denominator: `lost_packets` is a QUIC-packet counter,
 * but iroh 1.0's `PathStats` exposes no same-granularity `sent_packets` —
 * only `udp_tx.datagrams` (surfaced here as `sent_datagrams`, UDP-datagram
 * granularity). Dividing `lost_packets / sent_datagrams` mixes units and
 * yields a meaningless ratio. Use `lost_packets` as an absolute loss
 * indicator, not a percentage.
 */
export type NetworkStats = { path?: LinkPath, rtt_ms?: number, lost_packets: number, sent_datagrams: number, bytes_tx: number, bytes_rx: number, 
/**
 * How long the node has been ADMITTED to the fleet on the current
 * connection, in hub-monotonic milliseconds. Stamped when
 * `admit_inner` runs (post-HELLO on the established QUIC connection,
 * so this under-counts the true iroh connection age by the HELLO
 * round-trip). `None` when the node isn't currently connected. Reset
 * on every (re)admission.
 */
uptime_ms?: number, state: LinkState, };
