// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a node-directed chat test
 * ([`Higgs::node_chat_test`](crate::api::Higgs::node_chat_test)): one short
 * prompt relayed to a served instance on a SPECIFIC node over the live iroh
 * link, proving the hub→node→worker path end to end. Carries what the
 * operator needs to trust the link: which instance answered, what it said,
 * and how long the round trip (relay + full generation) took.
 */
export type NodeChatTestReport = { 
/**
 * The tested node's canonical iroh endpoint id (as passed in).
 */
endpoint_id: string, 
/**
 * The served instance id the test prompt was relayed to.
 */
served_id: string, 
/**
 * The model's reply text (may be empty if the model answered with
 * reasoning only under the small test budget).
 */
content: string, 
/**
 * OpenAI-style finish reason ("stop", or "length" when the test budget
 * truncated the reply — still a successful link proof).
 */
finish_reason: string, 
/**
 * Prompt token count reported by the remote engine.
 */
prompt_tokens: number, 
/**
 * Completion token count reported by the remote engine.
 */
completion_tokens: number, 
/**
 * Wall-clock milliseconds from dispatch to the final result — the full
 * hub→node relay plus generation, not a bare network ping.
 */
elapsed_ms: number, };
