// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardwareInfo } from "./HardwareInfo";
import type { InventoryWorker } from "./InventoryWorker";
import type { RuntimeInfo } from "./RuntimeInfo";

/**
 * A node's `M_NODE_INVENTORY` reply: host identity + resident workers + hardware/runtime.
 * The hub folds this into its per-node `NodeView` (§4.2.1). Hardware/runtime reuse the same
 * shapes as `M_NODE_SYSINFO` (they gained `Deserialize` for this).
 */
export type NodeInventory = { 
/**
 * Node hostname (best-effort; empty if unavailable).
 */
hostname: string, 
/**
 * Node OS, e.g. `"macos"` / `"linux"`.
 */
os: string, 
/**
 * Every worker resident on the node right now.
 */
workers: Array<InventoryWorker>, hardware: HardwareInfo, runtime: RuntimeInfo, };
