// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`M_NODE_LOG_LEVEL`] reply: the EFFECTIVE post-apply state of every
 * runtime log toggle on the node. Echoed so a caller stays in sync with the
 * daemon's actual state (including the fields it did NOT touch this call).
 */
export type NodeLogControlReply = { verbose: boolean, log_incoming_tokens: boolean, log_show_fields: boolean, };
