// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`M_NODE_LOG_LEVEL`] request params (hub → node): flip the node daemon's
 * `LogBus.verbose` gate LIVE. `None` = keep the current value; a bool
 * value overrides it (`true` admits DEBUG/TRACE into the `LogSource::Serve`
 * stream, `false` restores the INFO+ gate). This is the only knob — the
 * section badge that appears at the start of each log line is set at write
 * time by the tracing target, not by the wire.
 */
export type NodeLogControlParams = { verbose?: boolean, };
