// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`M_NODE_LOG_LEVEL`] reply: the EFFECTIVE post-apply verbosity on the
 * node. Echoed so a caller stays in sync with the daemon's actual state.
 */
export type NodeLogControlReply = { verbose: boolean, };
