// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInventory } from "./NodeInventory";
import type { UpdateFailed } from "./UpdateFailed";

/**
 * The hub's UI/API view of one node: its stable id, endpoint, whether it's currently
 * connected, its operator label, whether it is the LOCAL machine, and its last-fetched
 * inventory (host + resident workers + hardware/runtime). The Fleet UI renders local and
 * remote nodes with this one shape.
 */
export type NodeView = { node_id: number, endpoint_id: string, connected: boolean, 
/**
 * The local machine the server runs on (`true`) vs a paired remote node (`false`). The UI
 * hides Retire/Leave for the local node — there is nothing to un-pair.
 */
is_local: boolean, 
/**
 * Human label for the node. For a remote node this is the hub's allowlist label (the
 * node's friendly name, operator-renamable) — the fleet leaves it empty and the serve layer
 * fills it from the allowlist (the editable source of truth). For the local node it is the
 * instance's `config.json` name.
 */
label: string, inventory?: NodeInventory, 
/**
 * Age of the cached `inventory` snapshot in ms at the moment this view was
 * taken, computed hub-side from a DUAL wall+monotonic stamp taken at the
 * pull's start (see `PulledAt` — max of two lower bounds; errs stale-ward
 * only). The hub re-pulls inventory on connect and after lifecycle ops,
 * and a `fleet_events` node (T10) re-stamps it on every pushed state
 * change — so its rows read fresh in event time. Only an event-LESS
 * legacy node still relies on the debounced chat-end pull, and only there
 * does node-local activity age invisibly until the next pull. Absent for
 * the LIVE local card (its stats are read per request) and when there is
 * no cached inventory.
 */
inventory_age_ms?: number, 
/**
 * The node's self-reported higgs semver from its HELLO at (re)admission
 * (T14). Refreshed only by a reconnect — a node upgraded while admitted
 * shows its old version until it reconnects. Absent when no HELLO carried
 * one (pre-T14 admit paths) — the UI omits it, never fabricates.
 */
software_version?: string, 
/**
 * The node's LAST self-update FAILURE, re-reported in its HELLO on every admission until it
 * resolves (P4b (d)) — surfaced so the operator sees WHY a pushed update did not take (vs.
 * inferring it from `software_version` never advancing). Absent = the last update succeeded or
 * none was attempted; cleared once the node reports no failure while ALSO advancing off the
 * failed build (a same-version `None` from a legacy/dev binary does not erase it).
 */
update_failed?: UpdateFailed, 
/**
 * The HELLO-negotiated wire-protocol major for the node's CURRENT admission
 * (T14) — the same slot the per-load params gate reads ([HG078]). Absent =
 * the admission predates version reporting (effectively the floor, 1) or
 * the local card (no wire, no negotiation).
 */
protocol?: number, 
/**
 * The node's build TARGET triple from its HELLO (REL-P4e) — what the hub matches a release
 * asset against when it pushes a self-update. Refreshed per (re)admission, cleared at
 * retire. Absent for a legacy node that did not report it, or the local card.
 */
target?: string, 
/**
 * The node's acceleration VARIANT from its HELLO (`metal`/`cpu`/`cuda`) — the second half of
 * the release-asset selector. Same lifecycle as `target`; absent for a legacy node or the
 * local card.
 */
variant?: string, 
/**
 * Whether the node's CURRENT admission advertised the `update_by_version` capability —
 * the hub may send it a bare release VERSION and it self-fetches the assets from its own
 * configured `release_url`. `false` for a legacy node, a disconnected node's stale card,
 * and the local card (which is updated locally, not pushed).
 */
update_by_version: boolean, };
