// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Caps the user can place on how much of the machine a load may consume. The
 * suggester derives params *within* these caps instead of against the full
 * machine. Every field optional; `None` ⇒ uncapped (derive against the whole
 * machine using the default heuristics). A **suggester input only** — it
 * shapes the derived params, it is not itself a llama.cpp/worker param.
 */
export type ResourceBudget = { 
/**
 * Host RAM ceiling in bytes (CPU-resident weights + CPU KV + cpu_moe experts).
 */
max_ram_bytes?: number, 
/**
 * GPU VRAM ceiling in bytes (else: Σ GPU VRAM × headroom fraction).
 */
max_vram_bytes?: number, 
/**
 * Inference-thread ceiling (caps `n_threads` / `n_threads_batch`).
 */
max_cpu_threads?: number, };
