// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RoPE context-scaling type, mirroring the `llama-cpp-2` 0.1.139 wrapper's
 * `RopeScalingType` variants (`Unspecified`/`None`/`Linear`/`Yarn`). NOTE the
 * 0.1.139 wrapper omits the sys-level `LongRope` — reachable only via a newer
 * wrapper or raw FFI, so it is intentionally absent here.
 */
export type RopeScalingType = "Unspecified" | "None" | "Linear" | "Yarn";
