// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const RopeScalingType = {
    Unspecified : "Unspecified",
    None        : "None",
    Linear      : "Linear",
    Yarn        : "Yarn",
} as const;

export const { Unspecified, None, Linear, Yarn } = RopeScalingType;

export type RopeScalingType = (typeof RopeScalingType)[keyof typeof RopeScalingType];
