// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inference engine/runtime identity.
 */
export type RuntimeInfo = { 
/**
 * Engine name — always `"llama.cpp"` in v1.
 */
engine: string, 
/**
 * Compute backend: `"Metal"` on macOS, else `"CPU"`.
 */
backend: string, 
/**
 * Engine version reported at runtime by `ggml_version()` (e.g. `"0.9.7"`) —
 * the actual vendored ggml/llama.cpp engine version.
 */
version: string, 
/**
 * `llama-cpp-2` Rust binding crate version (e.g. `"0.1.139"`) — the wrapper
 * the engine is driven through, distinct from the engine version above.
 */
binding: string, };
