// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlamaCppSamplingParams } from "./LlamaCppSamplingParams";

/**
 * Engine-tagged **sampling-parameter umbrella**, mirroring [`LoadParams`].
 * `SamplingParams::LlamaCpp(LlamaCppSamplingParams)` today. Carried by
 * [`GenParams`] and persisted alongside a tuning profile.
 */
export type SamplingParams = { "engine": "LlamaCpp" } & LlamaCppSamplingParams;
