// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const Scope = {
    Chat   : "chat",
    Models : "models",
    Admin  : "admin",
} as const;

export const { Chat, Models, Admin } = Scope;

export type Scope = (typeof Scope)[keyof typeof Scope];
