// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const SplitMode = {
    None  : "None",
    Layer : "Layer",
    Row   : "Row",
} as const;

export const { None, Layer, Row } = SplitMode;

export type SplitMode = (typeof SplitMode)[keyof typeof SplitMode];
