// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multi-GPU split mode, mirroring `llama-cpp-2`'s `LlamaSplitMode`
 * (`None`/`Layer`/`Row`). Single-GPU/Metal target ⇒ derivation deferred;
 * the default is a no-op. Mapped to the wrapper enum inside `llamacpp/mod.rs`.
 */
export type SplitMode = "None" | "Layer" | "Row";
