// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardwareInfo } from "./HardwareInfo";
import type { HiggsServerConfig } from "./HiggsServerConfig";
import type { RuntimeInfo } from "./RuntimeInfo";

/**
 * The `system` control-op response (formerly `GET /api/higgs/system`):
 * hardware + runtime + server config.
 */
export type SystemInfo = { 
/**
 * Host hardware (CPU, RAM, live load).
 */
hardware: HardwareInfo, 
/**
 * Inference engine + backend.
 */
runtime: RuntimeInfo, 
/**
 * Read-only effective server config (scan dirs, load defaults, bind host).
 */
config: HiggsServerConfig, };
