// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtxLen } from "./CtxLen";
import type { GpuLayers } from "./GpuLayers";
import type { KvCacheKind } from "./KvCacheKind";

/**
 * User-pinned load params for a turbotune run — each `Some` value is
 * applied to the benchmark seed verbatim and EXCLUDED from the candidate
 * search (turbotune measures only the unpinned dimensions).
 */
export type TunePins = { 
/**
 * Pin the context window (e.g. `Fixed { n: 16384 }`).
 */
ctx_len?: CtxLen, 
/**
 * Pin the GPU offload — suppresses the half-layers candidate rung.
 */
gpu_layers?: GpuLayers, 
/**
 * Pin the K-cache type — suppresses the KV-quant candidate rungs.
 */
type_k?: KvCacheKind, 
/**
 * Pin the V-cache type — suppresses the KV-quant candidate rungs.
 */
type_v?: KvCacheKind, };
