// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitReport } from "./FitReport";
import type { LoadParams } from "./LoadParams";
import type { ResourceBudget } from "./ResourceBudget";
import type { SamplingParams } from "./SamplingParams";
import type { TuneProvenance } from "./TuneProvenance";

/**
 * The suggester's output: a full parameter set, fit verdicts, rationale, and
 * provenance. The button's suggested numbers populate the editable load-params
 * fields; the user can hand-adjust before loading. `load`/`sampling` are the
 * engine umbrellas (the `LlamaCpp` variant today).
 */
export type TuneSuggestion = { 
/**
 * The model id this suggestion is for.
 */
id: string, 
/**
 * Suggested load parameters (the umbrella; `LlamaCpp` variant).
 */
load: LoadParams, 
/**
 * Suggested sampling parameters (the umbrella; `LlamaCpp` variant).
 */
sampling: SamplingParams, 
/**
 * GPU VRAM fit verdict for the suggested load.
 */
vram_fit: FitReport, 
/**
 * Host RAM fit verdict for the suggested load.
 */
ram_fit: FitReport, 
/**
 * Human-readable notes explaining the non-default choices + the verdict.
 */
rationale: Array<string>, 
/**
 * Where the values came from.
 */
provenance: TuneProvenance, 
/**
 * The caps the suggestion was derived within (echoed for a re-tune).
 */
budget: ResourceBudget, };
