// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceBudget } from "./ResourceBudget";
import type { TuneMode } from "./TuneMode";
import type { TunePins } from "./TunePins";

/**
 * Request body for the `tune` control-op (`Higgs::tune`, formerly
 * `POST /api/higgs/models/tune`; the model id is in the body, not the path —
 * higgs ids are slashed/colon'd).
 */
export type TuneRequest = { 
/**
 * HuggingFace repo id (or `ollama/name:tag`) of the model to tune.
 */
id: string, 
/**
 * Suggest (default, cheap) vs Benchmark (explicit, offline — P2). Omittable
 * — `None` ⇒ `Suggest` server-side.
 */
mode?: TuneMode, 
/**
 * Optional resource caps to derive within.
 */
budget?: ResourceBudget, 
/**
 * BENCHMARK-mode pins: hold these load params fixed while turbotune
 * searches the rest. A pinned KV cache type suppresses the KV-quant
 * candidate rungs; pinned GPU layers suppress the half-layers rung.
 * Ignored in `Suggest` mode (the analytical suggestion stays free —
 * the user edits it in the UI and loads with explicit params).
 */
pins?: TunePins, };
