// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const TuneProvenance = {
    Heuristic : "Heuristic",
    Card      : "Card",
    Bench     : "Bench",
} as const;

export const { Heuristic, Card, Bench } = TuneProvenance;

export type TuneProvenance = (typeof TuneProvenance)[keyof typeof TuneProvenance];
