// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a suggestion's values came from — surfaced so the UI can label them.
 */
export type TuneProvenance = "Heuristic" | "Card" | "Bench";
