// AUTO-GENERATED — do not edit. Regenerated by `cargo test`.
// Backed by Rust enum via `#[derive(TsConstEnum)]` in `higgs-macros`.

export const TuneMode = {
    Suggest   : "suggest",
    Benchmark : "benchmark",
} as const;

export const { Suggest, Benchmark } = TuneMode;

export type TuneMode = (typeof TuneMode)[keyof typeof TuneMode];
