// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node's LAST self-update FAILURE — the node reports it in its next HELLO
 * ([`HelloParams::update_failed`]) and the hub surfaces it in the fleet view
 * ([`crate::node::fleet::NodeView::update_failed`]) so the operator learns WHY a pushed update
 * did not take (vs. inferring it from the version never advancing). Re-reported on EVERY HELLO
 * until the failure genuinely resolves (a successful apply, or the node advancing off the failed
 * version) — a valid HELLO reply does not prove the hub stored it, so the node never clears it on
 * the reply alone.
 */
export type UpdateFailed = { 
/**
 * The version the node is running NOW — the one it rolled back to, or stayed on when the
 * apply failed before ever flipping `current`.
 */
from: string, 
/**
 * The version the failed push TARGETED (from the manifest, or the push's `target_version`
 * when the failure preceded manifest parse). Empty if it could not be determined.
 */
to: string, 
/**
 * A short, sanitized reason — an HG code + phase, e.g. `HG084 artifact sha256 mismatch` or
 * `crash-looped on boot — rolled back`. Never free-form peer text (see `sanitize_version`).
 */
reason: string, };
